### ISSUE TITLE
软件真的非常非常棒！解决大问题了~~~

### ISSUE THREAD

**Issue by o000u** [abgox/InputTip#1]
作者真的很无私很负责，感恩感谢！！

**Comment by abgox** [comment]
- 在 v1 版本中，提示框是一直显示的，因为我希望它实时显示当前输入状态，而不只是在输入时。
- 如果不希望受到提示框的打扰，建议使用 v2 版本，v2 版本中，是通过不同的鼠标样式来区分中英文状态的，这对于鼠标使用过程中的打扰是最少的。
- 我个人也是使用 v2 版本，我认为它更合理，对鼠标使用体验的侵入性最低。
- 至于这两个不同版本我认为本身是没有什么问题的，从两个版本中选择适合自己的使用即可。

**Comment by abgox** [comment]
- 如果你是希望当输入时才显示提示框的话，你可以看看这个项目
- [ImTip](https://github.com/aardio/ImTip)

**Comment by o000u** [comment]
> * 如果你是希望当输入时才显示提示框的话，你可以看看这个项目
> * [ImTip](https://github.com/aardio/ImTip)

嗯嗯，收到回复很开心！！事实上我一开始用的老版本，后来用最新版后发觉之出院的一些问题都得到了不同程度解决，所以就去掉了问题，目前先用着v2，看看一段时间体验后怎样，如有建议还会再来骚扰大侠的，哈哈哈~~~对作者的认真负责再次感恩感谢！！

**Comment by Cold-Stars** [comment]
这软件真棒
