### ISSUE TITLE
[Bug]: 偶尔会弹出一个错误对话框

### ISSUE THREAD

**Issue by only4freedom** [abgox/InputTip#10]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

无法复现,仅在使用中偶尔会弹出错误对话框.已经确定是inputtip导致的.

### 实际发生了什么?

![Uploading Snipaste_2024-09-18_14-31-02.png…]()

**Comment by only4freedom** [comment]
![Snipaste_2024-09-18_14-31-02](https://github.com/user-attachments/assets/9e82b6be-53f5-4eec-bcfa-4a20fd2f0b63)
如图

**Comment by abgox** [comment]
![image](https://github.com/user-attachments/assets/9123394f-2e9b-494f-b827-a05b904a3bb4)
- 首先，这个错误对话框不是由 `InputTip` 产生
- 其次，`InputTip` 中没有任何逻辑代码和 `explorer.exe` 相关
- 如果你确定是由 `InputTip` 引起，那么大概率是因为获取光标位置方法内部的 dll 调用导致的，但是这些 dll 调用是通用的，我不知道具体的错误原因

---
- 你可以尝试把这个配置设置为 `0` 使用一段时间，如果不再出现这个错误弹窗，那应该就是 dll 调用的问题了
- 不过即使确定是 dll 调用的问题，也难以解决
![image](https://github.com/user-attachments/assets/e8e73cee-f435-4347-b36f-a48acba7c657)

**Comment by abgox** [comment]
- 一般有问题，也只能是 获取光标位置的 dll 调用有问题，
- 如果在文件管理器中显示方块符号不是刚需的话，建议直接将 `explorer.exe` 添加到 隐藏输入法状态的应用列表中

![image](https://github.com/user-attachments/assets/9d33d23c-466d-4d87-9300-8e841f13348d)

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可

**Comment by lhuanyun** [comment]
我也刚使用了360文件夹，但是我没有让他接管资源管理器，
我当前的360管理器版本为1.0.0.1150.
iinputtip ut版本为2025.07.20
也出现了此错误，当前我尝试将inputtip启动的时候设置管理员运行。
