### ISSUE TITLE
[Request]: 状态栏隐藏

### ISSUE THREAD

**Issue by HuangLiang0927** [abgox/InputTip#103]
### 描述这个功能请求

斗胆提一下，能不能支持一下右下角状态栏图标隐藏，我知道你是为了方便配置，但是你可以把状态栏隐藏的开关放到安装目录里面。你明白我的意思吧

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by abgox** [comment]
1. 我不认为这是一个合理的需求
2. 如果确实不想在右下角看到 `InputTip` 的软件图标，将其拖放到下图所示位置即可

![image](https://github.com/user-attachments/assets/198d177c-5ffa-431a-9bd3-2c74176c6e5e)
