### ISSUE TITLE
[Request]: 能不能增加一个Shake to Find Cursor功能

### ISSUE THREAD

**Issue by lcpmgh** [abgox/InputTip#104]
### 描述这个功能请求

一个建议，最近更改光标后，有时候经常找不见光标在哪，有个开源项目实现了windows系统下，晃动鼠标放大光标的功能，比系统自带的按ctr找光标方便很多，如果能集成到InputTip中就更好了，希望作者可以考虑一下：https://github.com/MrBeanCpp/CursorFinder

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by abgox** [comment]
- `InputTip` 不是一个集合式的工具，它只负责特定的这部分功能
- 找光标这个功能，我更推荐使用 [PowerToys](https://github.com/microsoft/PowerToys) 这个微软官方的小功能集合
