### ISSUE TITLE
[Request]: 占用cpu资源过高

### ISSUE THREAD

**Issue by DostGit** [abgox/InputTip#106]
### 描述这个功能请求

![image](https://github.com/user-attachments/assets/e948aa21-4a42-40b7-b0ea-c9ad67280434)

不知道为什么会占用这么多cpu资源，有时候甚至达到了5%、6%，cpu是amd3900x

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by DostGit** [comment]
好的，感谢解疑

**Comment by DostGit** [comment]
![image](https://github.com/user-attachments/assets/7bdbbea6-82f6-4f6b-8536-23978245cef5)

恢复正常了

**Comment by DostGit** [comment]
我似乎发现问题在哪里了，使用的是2.26，当设置-无操作时，符号在多少毫秒后隐藏多少秒时，cpu资源就会出现远超没设置时的占用，当设置为0的时候，资源占用非常小。这是否能够优化呢？
![image](https://github.com/user-attachments/assets/bee8d178-9a2b-4f38-b861-8ca36e1ee045)

**Comment by abgox** [comment]
- 这是个好消息，因为这个问题，在我这里能够复现
- 我先看看具体是什么原因导致的

**Comment by abgox** [comment]
- `v2.26.1` 已经修复
