### ISSUE TITLE
管理员权限启动

### ISSUE THREAD

**Issue by zdjdj5201978** [abgox/InputTip#107]
请问是否可以取消管理员权限启动，因为工作状态下，管理员权限运行被限制了，这样无法运行本软件。

**Comment by abgox** [comment]
> [!NOTE]
>
> - 因为以下原因，可能无法正常运行 `InputTip.exe`
>   - 没有管理员权限
>   - 杀毒软件或防火墙阻止了 `InputTip.exe` 运行
>   - ...
> - 你可以尝试以下方案:
>   1. 克隆项目仓库到本地
>   2. 安装 [AutoHotkey v2](https://www.autohotkey.com/)
>   3. 直接运行项目中的 `InputTip.ahk` 文件
>      - `src\v2\InputTip.ahk`
