### ISSUE TITLE
[Bug]: 使用微信输入法在vscode里不能识别中英文，只会以英文显示

### ISSUE THREAD

**Issue by qstdnx** [abgox/InputTip#109]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.6.2

### 你正在使用什么 Windows 系统版本?

Windows 11 专业版23H2 (OS 内部版本 22631.4460)

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

vscode

### bug 复现步骤

见下图

### 实际发生了什么?

如图
![1](https://github.com/user-attachments/assets/832c35c4-804e-447a-8e9c-93ee2db0b3e9)
在vscode里中英文都显示英文，但是大写正常。
如果你不能复现，那说明是我电脑问题，无视这个issue!

### 还有其他你想要补充的信息吗？

可能是我电脑问题

**Comment by abgox** [comment]
- [输入法模式的已知问题](https://inputtip.pages.dev/FAQ/#%E8%BE%93%E5%85%A5%E6%B3%95%E6%A8%A1%E5%BC%8F%E7%9A%84%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98)
- 这是使用 `模式2 - 通用`(默认) 在极少数情况下可能导致突然无法识别中英文的问题
   -  重启 vscode 或 InputTip 应该能解决
- 如果在你的使用环境中，这个问题的发生频率很高的话，就试试 `模式1 - 通用`

**Comment by qstdnx** [comment]
> * [输入法模式的已知问题](https://inputtip.pages.dev/FAQ/#%E8%BE%93%E5%85%A5%E6%B3%95%E6%A8%A1%E5%BC%8F%E7%9A%84%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98)
> * 这是使用 `模式2 - 通用`(默认) 在极少数情况下可能导致突然无法识别中英文的问题
>   
>   * 重启 vscode 或 InputTip 应该能解决
> * 如果在你的使用环境中，这个问题的发生频率很高的话，就试试 `模式1 - 通用`

模式1和模式2都试过，都不会触发中英转化，看来是我电脑环境问题，无视这个issue。
