### ISSUE TITLE
[Request]: 可否方块里面直接文字提醒

### ISSUE THREAD

**Issue by ooing** [abgox/InputTip#11]
### 描述这个功能请求

比如中文情况下   方块里面是  中     如果是英文情况下 方块里面是 E 或者 英   
比较直接直观，不然还得去看颜色

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by abgox** [comment]
- 实际上，用习惯之后，看到不同颜色，就会本能的知道输入法状态，这也很直观
- 如果想要显示字符，你应该使用 v1，不应该使用 v2

**Comment by ooing** [comment]
@abgox    v2好像是趋势，v2支持文字比较难吗  好奇

**Comment by abgox** [comment]
- 在最新的版本中，添加了显示字符的配置
- 托盘菜单 > `更改配置` > `是否显示文本字符`

**Comment by ooing** [comment]
谢谢
