### ISSUE TITLE
[Bug]: 焦点从非黑名单应用切换到黑名单应用时， 提示图标不会消失

### ISSUE THREAD

**Issue by scrpr** [abgox/InputTip#110]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.26.2

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

Any

### bug 复现步骤

如图，资源管理器在黑名单中，而qbittorent不在黑名单中
![排除名单时不会消失](https://github.com/user-attachments/assets/c46443c4-dfe7-4ffb-bf54-9593770270fd)

### 期望结果

无论程序是否在黑名单，切换焦点时都应更新检测状态

### 实际发生了什么?

焦点从非黑名单应用切换到黑名单应用时， 提示图标不会消失

**Comment by abgox** [comment]
- 我将 `explorer.exe` 设置为黑名单，切换之后符号是会消失的
- 不过再切换回去符号不会立即出现，需要多点一次，或者更新光标位置，这个问题后面改改

![recording](https://github.com/user-attachments/assets/c7983ed2-50d4-444a-a598-b1dacc4073be)
