### ISSUE TITLE
ACC_list 作用是什么

### ISSUE THREAD

**Issue by H1DDENADM1N** [abgox/InputTip#113]
我注意到有将explorer.exe加入ACC_list，但是无调用到ACC_list。是不是需要特殊处理但是忘写了。

https://github.com/abgox/InputTip/blob/0de4690145c6084ff4f84b4e6ff344448a4631c4/src/v2/InputTip.ahk#L2138

**Comment by abgox** [comment]
- 没啥作用，这一行只是忘记注释或者删除了
- 在 Win11 中，获取它们的光标位置没有什么问题，Win 10 中好像有点问题，不过可以直接添加黑名单解决
