### ISSUE TITLE
[Bug]: 在Win11上，项目貌似和托盘区冲突

### ISSUE THREAD

**Issue by JustGoi** [abgox/InputTip#114]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.26.5

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

没有

### bug 复现步骤

在以管理员方式运行程序后，我的电脑托盘区不能正常显示，我打开托盘区后它会出现类似“闪退”，或显示残缺的问题
这是bug图片：
![图片1](https://github.com/user-attachments/assets/2a60bb19-bdd4-4617-b197-ff660e6a5b3b)
![图片3](https://github.com/user-attachments/assets/bd331ef5-04a7-49e6-8275-1787287a51c7)

### 期望结果

这是我退出软件后正常显示的托盘
![图片2](https://github.com/user-attachments/assets/f4073981-72b5-4b32-ad23-35ed7b422d12)

### 实际发生了什么?

我提供了bug图片

**Comment by wcool1** [comment]
me,too。不仅仅是托盘区，还有一些windows原生应用也会冲突比如截图

**Comment by abgox** [comment]
- [窗口兼容性问题](https://inputtip.pages.dev/FAQ/#%E7%AA%97%E5%8F%A3%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98)
