### ISSUE TITLE
[Bug]: 两种输入法对微软拼音都不支持

### ISSUE THREAD

**Issue by 197895** [abgox/InputTip#119]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.27.0

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

所有

### bug 复现步骤

1. 
**貌似每一种方法都对微软拼音不支持**
![image](https://github.com/user-attachments/assets/65f1fb92-c10c-4e81-b141-ce5381d271c7)
2. 
在我的电脑上,
**通用1对讯飞输入法不支持;
通用2讯飞输入法会导致中英颠倒**
![image](https://github.com/user-attachments/assets/54cfa9ff-e2a7-41e0-81e2-af809c6b3b91)

3. **在window界面无法显示**
![image](https://github.com/user-attachments/assets/b44c69ab-d338-4eb9-a310-78aa6d82ec44)

### 期望结果

按照兼容情况说明,对微软和讯飞输入法都应该兼容才对

### 实际发生了什么?

1. 
**貌似每一种方法都对微软拼音不支持**
![image](https://github.com/user-attachments/assets/65f1fb92-c10c-4e81-b141-ce5381d271c7)
2. 
**通用1对讯飞输入法不支持;
通用2讯飞输入法会导致中英颠倒**
![image](https://github.com/user-attachments/assets/54cfa9ff-e2a7-41e0-81e2-af809c6b3b91)

3. **在window界面无法显示**
![image](https://github.com/user-attachments/assets/b44c69ab-d338-4eb9-a310-78aa6d82ec44)

**Comment by abgox** [comment]
> 通用1对讯飞输入法不支持;
> 通用2讯飞输入法会导致中英颠倒

- 兼容情况说明里，`模式1 - 通用` 和 `模式2 - 通用` 就没有说兼容了讯飞输入法
- 讯飞输入法要使用特殊的 `模式4 - 讯飞输入法`

![image](https://github.com/user-attachments/assets/a37ee2c6-0368-4bc5-910f-ebc4610a92a7)

**Comment by abgox** [comment]
- 对于微软拼音，默认的 `模式2 - 通用` 是支持的

![recording](https://github.com/user-attachments/assets/fb073f85-270b-43bb-980d-1c925975ed61)
