### ISSUE TITLE
[Bug]: 在JetBrains IDE中，使用iDEA Vim插件，会导致指示方框显示异常

### ISSUE THREAD

**Issue by Ruikoto** [abgox/InputTip#12]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

在JetBrains IDE中（我用的Rider），使用iDEA Vim插件，在INSERT状态下，指示器会在错误的位置卡住不动或是直接消失，无法正常使用。

### 实际发生了什么?

指示器会在错误的位置卡住不动或是直接消失，无法正常使用。

### 还有其他你想要补充的信息吗？

软件很好用，感谢作者的辛苦开发！

**Comment by Ruikoto** [comment]
*以及失去焦点的时候这个指示器会跑到屏幕左上角去
![image](https://github.com/user-attachments/assets/e03b6edc-4c00-4604-9fdf-5a6787a8d25e)

**Comment by Ruikoto** [comment]
以及推荐一套配色，用纯色实在是有点不好看
英文 #03A2FE
中文 #FF6A43
大写锁定 #705AD6

**Comment by abgox** [comment]
- jetBrains 系列软件，光标是由软件自己画的，所以识别不到
- 这个系列的软件我记得有一个改变光标的插件 [Smart Input](https://plugins.jetbrains.com/plugin/20575-smart-input)
- 我觉得它可能比 `InputTip` 更适合，所以更建议在 jetBrains 系列软件中直接隐藏方块符号

**Comment by Ruikoto** [comment]
> > 以及推荐一套配色，用纯色实在是有点不好看 英文 #03A2FE 中文 #FF6A43 大写锁定 #705AD6
> 
> * 在我看来，纯色只能算一般
> * 好不好看这一点太主观，只是我觉得纯色适合作为默认值
> * 所以我更希望用户自己去配置自己喜欢的颜色，甚至于不需要按照我的逻辑，红色中文、蓝色英文、绿色大写锁定，应该是按照自己喜欢的方式，自己的逻辑来灵活的配置它们

就平时的观察来看，大部分用户包括开发者其实并不会调（或者说“挑”）配色，而且是在没有内置调色板的情况下。我觉得还是内置一个开箱即用的，大部分情况下比较好看的配色方案会更好一些。
