### ISSUE TITLE
[Bug]: InputTip.JAB.JetBrains.exe应用无法自动打开

### ISSUE THREAD

**Issue by ilfann** [abgox/InputTip#123]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.27.2

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

JetBrains IDE

### bug 复现步骤

生成的InputTip.JAB.JetBrains.exe应用无法由InputTip.exe控制打开，重启主应用后InputTip.JAB.JetBrains.exe需要手动打开

### 实际发生了什么?

https://github.com/user-attachments/assets/bac5a46a-2aa2-4f0a-808c-94fdf016bc67

**Comment by abgox** [comment]
- `2.28.0` 版本中应该有修复
- 但 `2.28.0` 的正式发布，还要再等等

**Comment by ilfann** [comment]
感谢
