### ISSUE TITLE
[Bug]: 两个显示器的时候，那个块标，有时候会出现在另外一个显示器上

### ISSUE THREAD

**Issue by xuyisoso** [abgox/InputTip#13]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

发生场景，在使用notepad++编辑文本的时候。
（在浏览器chrome里面貌似又是正常的，浏览器拖到左边或者右边都能正常。）
![image](https://github.com/user-attachments/assets/f1e7855a-c86d-4060-85e0-78953f883b84)

### 实际发生了什么?

两个显示器的时候，那个块标，有时候会出现在另外一个显示器上

**Comment by abgox** [comment]
- 因为获取光标位置方法，有时候获取到的值会有问题
- 我只能尽量让它们正常，覆盖到一般的使用情况，但一些特殊情况，我也没有办法

**Comment by abgox** [comment]
- 已经在新版本 `v2.18.4` 中修复
- 重启更新版本即可
   - 如果重启没有检查到更新，直接在项目 Release 中下载最新版本
