### ISSUE TITLE
[Request]: 输入焦点检测

### ISSUE THREAD

**Issue by 2531** [abgox/InputTip#14]
### 描述这个功能请求

是否可以实现光标不在输入焦点时隐藏小方块。

---

另外写这段文字的时候发现方块不在光标处，win10， chrome 128
![image](https://github.com/user-attachments/assets/9664e50a-bc5a-4ca8-a313-55126b78e4c3)

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by abgox** [comment]
- 做不到的
- 当获取光标位置的方法运行后，会返回坐标的位置，但是我没有办法知道这个获取到的光标位置是否正确的
- 会有许多情况可能导致获取到的光标位置有问题，我只能尽量保证大多数情况下没有问题
- 所以，鼠标样式的改变是最稳定的方案

**Comment by lingfengyu-dreaming** [comment]
https://blog.csdn.net/scy261983626/article/details/122816301
这个博客讲了一些判断光标的方法，能不能借助鼠标状态和单击事件来判断焦点状态

**Comment by abgox** [comment]
> https://blog.csdn.net/scy261983626/article/details/122816301 这个博客讲了一些判断光标的方法，能不能借助鼠标状态和单击事件来判断焦点状态

- 实际是做不到的，有许多情况需要考虑
- 比如判断鼠标是不是工字型，那我点了后，移开了，正好放在一个可点击链接上，那不就是一个小手了吗？
- 这个时候，我依旧是在输入状态，但鼠标样式则变成了一个小手

- 现在最新版本 `2.21.11`，基本上解决了这样的错位问题，也不必考虑这个了
