### ISSUE TITLE
[Bug]: 在OneNote中无法打字，添加为特殊软件后可正常打字。

### ISSUE THREAD

**Issue by K7Rain** [abgox/InputTip#15]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

OneNote随便一个笔记页面，用输入法打字

### 实际发生了什么?

本人使用的是搜狗输入法，模式2。也尝试了模式1，同样出现bug

**Comment by abgox** [comment]
- 这是获取光标位置的 dll 调用导致的问题
- 现在改为了另一种方法调用
   - 不过另一种方法有概率获取不到光标位置，导致方块符号无法显示，暂时没有办法解决

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可
