### ISSUE TITLE
[Request]: 单独设置 中/英状态 时不显示提示

### ISSUE THREAD

**Issue by YukonKong** [abgox/InputTip#17]
### 描述这个功能请求

输入法状态要么中文，要么英文，没必要各设置一种颜色。
比如 中文状态不显示方块，英文状态显示方块，更容易判断。

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- 最新版本，将颜色留空，就不显示方块了
- 对于字符也是一样的，字符留空，也就不显示了
