### ISSUE TITLE
[Bug]: 模式2，偶尔无法自动切换到英文状态

### ISSUE THREAD

**Issue by gbsix** [abgox/InputTip#18]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

win10，搜狗输入法。把看图软件FSViewer.exe添加到自动英文，打开图片有时候会自动切换到英文，有时候中文状态闪一下，切换到英文状态失败。

### 期望结果

强制自动切换而无需快捷键。

### 实际发生了什么?

自动切换到英文失败。

**Comment by abgox** [comment]
- 在我的电脑中运行正常
![demo1](https://github.com/user-attachments/assets/ea33da36-5228-4088-8319-d62dd568d017)

**Comment by abgox** [comment]
> 另外， 如果软件自动切换到大写，在打开其他软件窗口时不能恢复到默认状态，会一直显示大写，需要手动关闭。 期望：在离开自动大写/英文/中文的程序后，可以自动恢复所在程序的输入法默认状态。

- 自动切换只是切换，而不会恢复
- 只要其他软件窗口中没有定义自动切换，就不会再改变输入法状态

**Comment by abgox** [comment]
- 自动切换是基于识别当前窗口的进程程序名称的
- 设置了 `FSViewer.exe` 自动切换到英文
- 如果当前激活的窗口的进程程序名称不是 `FSViewer.exe`，是不会自动切换的

**Comment by abgox** [comment]
- 那就不知道了，可能是切换输入法状态的方法没有生效
- InputTip 使用的哪个版本，如果不是最新版本，重启检查一下更新，或者直接在 Release 中下载
- 最近的有一个新版本的修复，加了一个兜底的模拟 Shift 切换操作
