### ISSUE TITLE
大写锁定提示

### ISSUE THREAD

**Issue by jphaha** [abgox/InputTip#2]
作者考虑增加大写锁定提示

**Comment by abgox** [comment]
- 没考虑过，应该很少有频繁切换大写锁定的场景
- 对于大多数笔记本电脑，都有内置的大写锁定提示
- 如果要添加的话，也没有一个很好的提示风格
- 现在大多数有大写锁定提示的处理方式，都是在屏幕的某个地方固定显示，我觉得这具有侵入性，我不喜欢

**Comment by abgox** [comment]
- 貌似可行，后续尝试添加
- 在 v2 中，默认使用红色代表中文、蓝色代表英文，可以再加一个绿色代表大写锁定
- 在 v1 中，可以直接在显示框后加一个符号或者 `Caps` 表示大写锁定

**Comment by jphaha** [comment]
所见略同，中英文的大写都是一样的，也不用区分是中文大写还是英文大写，再加一个状态就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 凌晨1:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [abgox/InputTip] 大写锁定提示 (Issue #2)














  
貌似可行，后续尝试添加
 
在 v2 中，默认使用红色代表中文、蓝色代表英文，可以再加一个绿色代表大写锁定
 
在 v1 中，可以直接在显示框后加一个符号或者 Caps 表示大写锁定

**Comment by abgox** [comment]
- 已经添加，请前往 [releases](https://github.com/abgox/InputTip/releases) 中下载最新版本
- v1版本: v1.1.0
- v2版本: v2.2.0
