### ISSUE TITLE
[Request]: 输入状态仅显示x秒

### ISSUE THREAD

**Issue by hhuimie** [abgox/InputTip#20]
### 描述这个功能请求

目前多多少少有遮挡的情况, 能否添加个当激活输入框或者切换中英文的时候, 仅显示比如2秒的输入状态

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by abgox** [comment]
- 如果有遮挡，你应该添加偏移量

**Comment by hhuimie** [comment]
![image](https://github.com/user-attachments/assets/4a9e0aa8-15e4-4fda-84e0-333f6576705a)
这个提示是否有必要一直存在, 一般人不是在点击输入框或者切换状态的时候看一下就够了吗?

**Comment by abgox** [comment]
- 如果不一直存在，我怎么会知道你什么时候想要切换状态呢？那又应该什么时候显示呢？
- 如果只是需要在点击输入框的时候看一下，那其实没必要使用方块符号，只保留鼠标样式的改变就够了
- 如果是切换状态的时候看一下，那操作就更多余了
   - 如果当前输入法是中文的，我想要输入中文，但是我不知道当前的状态，我切换一下状态，然后显示这个符号了，但是状态也切换成了英文，我还得再切换一次，变回原本的中文状态

**Comment by abgox** [comment]
- 你也可以通过将一些状态的颜色值设置为空，这样它的显示频率就没有那么高了
- 比如: 
    - 你只希望在中文状态下，显示这个符号，你完全可以将英文状态下的方块符号颜色和大写状态下的方块符号颜色设置为空
    - 这样的话，就只有在中文状态下，这个方块符号才会显示

**Comment by hhuimie** [comment]
![image](https://github.com/user-attachments/assets/fa000ca9-1d1e-4e88-ac50-b1eadf014f96)
imtip有这个功能, 我不知道这里能不能提别家的产品, 请见谅

**Comment by abgox** [comment]
- 当然可以提，我也推荐过 `imTip` ,找到适合自己的就行，也不一定要使用 `InputTip`
- 但是 `InputTip` 要的就是实时显示，所以应该不会添加这样的选项

**Comment by hhuimie** [comment]
> * 如果不一直存在，我怎么会知道你什么时候想要切换状态呢？那又应该什么时候显示呢？

我并不是程序员, 我并不知道软件怎么获取"我切换状态"的动作, 按照我朴实的理解, 就是我切换成英文, 方块就变色, 这样我也知道我切换成功了, 我不用打个字测试一下.

> * 如果只是需要在点击输入框的时候看一下，那其实没必要使用方块符号，只保留鼠标样式的改变就够了

有一种可能是别人也想保留原生鼠标之类的

> * 如果是切换状态的时候看一下，那操作就更多余了
>   
>   * 如果当前输入法是中文的，我想要输入中文，但是我不知道当前的状态，我切换一下状态，然后显示这个符号了，但是状态也切换成了英文，我还得再切换一次，变回原本的中文状态

如果当前是中文, 那么在我点击输入框的时候, 方块就提醒我是中文了, 就算两秒之后消失, 我应该也不至于就忘记了这个事情. 所以"当前是中文", "我想输入中文", "但是我不知道当前是不是中文", 这三个条件要同时实现貌似还挺难的, 除非是点击进输入框了, 但是人离开了一段时间, 回来继续输入, 但是因为相隔太久忘记了?
最后, 如果软件本身要的就是一直, 实时显示, 那确实我的建议就是多余了

**Comment by abgox** [comment]
> 就是我切换成英文, 方块就变色, 这样我也知道我切换成功了, 我不用打个字测试一下.

- 但是这是需要切换输入法的情况，如果不需要切换呢?如果当前输入法就是英文，你只需要输入英文就好了
- 这种情况下，如果不进行实时显示的话，软件就没有办法去判断应该在什么时候显示
- 在按下键盘的第一个字母按键的时候显示吗？但是这样的话，实际就没有作用了，相当于我已经按错了，需要按 `Backspace`(退格键)回删错误的输入，然后再切换输入法状态了

> 有一种可能是别人也想保留原生鼠标之类的

- 如果完全想保留原生鼠标，在任何输入法状态下都是原生鼠标样式的话，那确实没有办法通过鼠标判断
- 但如果不是想完全保留原生鼠标样式的话，是有一个方法方法的
- 比如:
   - 可以把英文状态下的鼠标样式设置为默认样式
   - 这样，在英文状态下，就会显示默认样式了
   - 一种变相的实现，默认的鼠标样式(浅色和深色的两种样式)也已经放入了 [鼠标样式包](https://inputtip.pages.dev/releases/v2/cursorStyle.zip) 里，可以直接使用

**Comment by hhuimie** [comment]
> 这种情况下，如果不进行实时显示的话，软件就没有办法去判断应该在什么时候显示

我不太明白一直显示的逻辑, 在我浅薄的认知里, 在非输入状态下, 切换输入法是没什么意义的, 可以忽略?
如果是在输入状态, 也就是激活了输入框的情况下, 如果每次激活输入框, 都已经显示x秒方块了, 应该就没问题了. 也就是我激活输入框的时候, 方块提醒我目前输入法是中文还是英文, 我自行判断是否要切换, 如果切换了, 方块再变色或者重新显示出来.
这种情况并不需要我输入第一个字母才能知道是中文还是英文
更进一步, 假设我真的激活输入框之后, 离开了一段时间, 回来之后并没有重新激活输入框, 忘记是中文还是英文了, 那还可以通过监控键盘或者鼠标的空闲时间, 比如超过1分钟没动过了, 当鼠标再次移动并且输入框属于激活状态的时候, 就重新显示方块提示

btw, 为什么提议添加仅显示x秒的功能, 还有个原因就是软件很难做到完美的兼容, 就比如现在我用chrome在回复, 这个方块有些时候是错位的, 也试过其他模式, 还是不行, 也不知道是哪个软件的问题.
![image](https://github.com/user-attachments/assets/6760cd48-86c2-4050-b4bd-caa34889e78b)

**Comment by hhuimie** [comment]
另外在我的浏览器上, 某些非输入框, 我左键三击选择文本的时候, 也会出现这个方块, 如下图
![image](https://github.com/user-attachments/assets/952b1051-90d3-49a3-949e-2980a006f916)

**Comment by hhuimie** [comment]
然后发现, 主页只打开网页, 什么都不动, 左上角也会出现, 即使是关闭所有扩展的情况下
![image](https://github.com/user-attachments/assets/3d3de134-5bd7-464e-ac50-c641047c864a)

**Comment by abgox** [comment]
> > 这种情况下，如果不进行实时显示的话，软件就没有办法去判断应该在什么时候显示
> 
> 我不太明白一直显示的逻辑, 在我浅薄的认知里, 在非输入状态下, 切换输入法是没什么意义的, 可以忽略? 如果是在输入状态, 也就是激活了输入框的情况下, 如果每次激活输入框, 都已经显示x秒方块了, 应该就没问题了. 也就是我激活输入框的时候, 方块提醒我目前输入法是中文还是英文, 我自行判断是否要切换, 如果切换了, 方块再变色或者重新显示出来. 这种情况并不需要我输入第一个字母才能知道是中文还是英文 更进一步, 假设我真的激活输入框之后, 离开了一段时间, 回来之后并没有重新激活输入框, 忘记是中文还是英文了, 那还可以通过监控键盘或者鼠标的空闲时间, 比如超过1分钟没动过了, 当鼠标再次移动并且输入框属于激活状态的时候, 就重新显示方块提示

- 实时显示，更多的是一种确定感吧，我能百分之百确定现在的状态到底是不是我想要的
- 不过添加一个多秒后消失，确实也算是一个合理的选项，后面尝试添加

**Comment by abgox** [comment]
- 非输入框，这就完全取决于能不能获取到光标位置了，但是因为兼容问题，有时候即使没有实际的光标，也能获取到虚拟的光标位置，这解决不了
   - 只是一般获取到的虚拟光标位置，不会造成严重的遮挡，勉强能接受
- 因为实际上，软件是没有办法知道当前是否是处于可输入的状态的

**Comment by hhuimie** [comment]
> * 非输入框，这就完全取决于能不能获取到光标位置了，但是因为兼容问题，有时候即使没有实际的光标，也能获取到虚拟的光标位置，这解决不了
>   
>   * 只是一般获取到的虚拟光标位置，不会造成严重的遮挡，勉强能接受
> * 因为实际上，软件是没有办法知道当前是否是处于可输入的状态的

这种兼容问题, 如果能通过设置仅显示x秒来抵消, 那就影响不大了.
不管怎么说, 谢谢您的开发, 确实方便了很多.

**Comment by hhuimie** [comment]
btw, 上面我提到的错位问题, 好像更新到2.15.0就没了
赞

**Comment by hhuimie** [comment]
![image](https://github.com/user-attachments/assets/79d13ad6-72a3-4767-9de1-7168895ac51d)
然而钉钉又有点错位了.

**Comment by abgox** [comment]
这种兼容性问题，很多，只能说，有一个，尽量就解决一个

**Comment by hhuimie** [comment]
![视频_2024-09-20_115140](https://github.com/user-attachments/assets/59e80e7a-62bb-4d5d-908d-e9583306271e)

**Comment by abgox** [comment]
- 钉钉桌面端的错位已经解决
- 配置项已经添加
- 最新版本 `v2.16.0`

![image](https://github.com/user-attachments/assets/8116e746-727d-428b-b9c4-1c772a12e909)

**Comment by hhuimie** [comment]
非常感谢, 但是目前测试下来好像无效哦, 不管改成1还是100毫秒, 都会一直显示, 即使不打字

**Comment by hhuimie** [comment]
另外看到官网的更新日志
> 方块符号隐藏后，在当前软件窗口的任何鼠标操作都不会再显示方块符号，直到下一次键盘按键操作或者切换到其他软件窗口才会重新显示

弱弱的问一句, 能不能再开放个选项, 就是"直到切换输入法或者切换到其他软件窗口才会重新显示".
要不然如果我一直打字的话, 按照说明还是会一直显示

**Comment by abgox** [comment]
![demo1](https://github.com/user-attachments/assets/c43ccc25-dd22-4994-81c2-c31bd4740861)

**Comment by abgox** [comment]
> 非常感谢, 但是目前测试下来好像无效哦, 不管改成1还是100毫秒, 都会一直显示, 即使不打字

- 如果鼠标光标样式修改没有开启就没有效果，因为代码没改全，我改一改
- 就加一个 `-1` 吧，如果设置为 `-1`，只有在切换输入法状态和切换软件窗口才显示

**Comment by abgox** [comment]
- 我想了一下，`InputTip` 终究是一个希望实时显示的提示工具，没有键盘操作时隐藏我觉得已经足够了
- 我重新看了整个 issue，我发现你的使用场景、使用习惯和 `ImTip` 非常契合，点击输入框和切换状态时才显示，`ImTip` 就是这样的。那你直接使用 `ImTip` 就好了，其实没有必要换成 `InputTip`

**Comment by hhuimie** [comment]
谢谢开发者, 我两个都用过, 实际体验, 兼容性还是inputtip好一点
