### ISSUE TITLE
[Bug]: 启动后自动闪退，请求协助

### ISSUE THREAD

**Issue by AnLazyOtter** [abgox/InputTip#21]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 https://inputtip.pages.dev/

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

以管理员身份运行：`E:\Program Files\InputTip\InputTip.exe` 
而后，闪退。
尝试手工调整INI：
- 是否修改光标：否
再次以管理员身份运行，能启动。
在”展示字符“与”不展示字符“之间切换，数次尝试后就再次出现了闪退的情况（能运行，托盘区能看到，1秒后程序没了）

### 期望结果

能常驻后台运行。

### 实际发生了什么?

未知原因闪退。

### 还有其他你想要补充的信息吗？

尝试翻了一下有没有日志，但是没找到相关文件。可否提供方法以收集日志、排障，不胜感激。

**Comment by abgox** [comment]
- 最新版本 `v2.15.0` 是有常驻的，你应该不是使用的最新版本，最新版本也刚更新

**Comment by abgox** [comment]
- 确实没有日志文件，软件也不希望去产生这些额外的文件，没有必要
- 软件产生的额外文件还是越少越好

**Comment by abgox** [comment]
- 安装最新的  `2.17.5` 版本试试
- 如果仍然有问题，再重开这个 issue

**Comment by AnLazyOtter** [comment]
> * 安装最新的  `2.17.5` 版本试试
> * 如果仍然有问题，再重开这个 issue
您好，尝试了一下微软拼音输入法（旧版）、小狼毫输入法0.16.1.0，还是会出现闪退（2.21.0.0）
![image](https://github.com/user-attachments/assets/3bac620b-cae6-4bbd-b21e-ee127db9aba4)

**Comment by abgox** [comment]
录个屏、或者弄个 gif，录一下整个闪退过程

**Comment by AnLazyOtter** [comment]
> 录个屏、或者弄个 gif，录一下整个闪退过程

@abgox 参见附件


https://github.com/user-attachments/assets/9b4bb8bc-0872-4ce9-8aa3-c17b95f07b64

**Comment by abgox** [comment]
- 是使用的最新版本吗？ 使用最新版本 `2.21.8` 试试呢？

**Comment by AnLazyOtter** [comment]
> * 是使用的最新版本吗？ 使用最新版本 `2.21.8` 试试呢？

2.21.11版本已经没问题了，感谢~

**Comment by AnLazyOtter** [comment]
> * 是使用的最新版本吗？ 使用最新版本 `2.21.8` 试试呢？

不好意思，出现了一些问题：
重启设备后，就又闪退了……
删除inputtip.exe之外的文件后再次启动，未能成功启动。
删除所有文件（清空文件夹E:\Program Files\InputTip）后，重新下载2.21.11版本，就又能启动了。
大约2分钟后弹窗报错，很遗憾没能截图下来。
再次清空文件夹并将下载的InputTip.exe复制到前述路径后，就又能用了……

**Comment by abgox** [comment]
那可能就需要等后续有报错，及时截图了

**Comment by AnLazyOtter** [comment]
> 那可能就需要等后续有报错，及时截图了

不好意思上一条没写完就误操作发出去了。
而后，排除变量法，再次重启，就无法使用了。换言之，目前测试下来：
首次启动->重启->再次启动->闪退
这个问题在我的设备上是100%复现的。

**Comment by abgox** [comment]
> > 那可能就需要等后续有报错，及时截图了
> 
> 不好意思上一条没写完就误操作发出去了。 而后，排除变量法，再次重启，就无法使用了。换言之，目前测试下来： 首次运行->重启计算机->再次运行InputTip->闪退 这个问题在我的设备上是100%复现的。

直接运行 `InputTip.exe` 软件本体试试呢？不运行快捷方式

**Comment by AnLazyOtter** [comment]
> > > 那可能就需要等后续有报错，及时截图了
> > 
> > 
> > 不好意思上一条没写完就误操作发出去了。 而后，排除变量法，再次重启，就无法使用了。换言之，目前测试下来： 首次运行->重启计算机->再次运行InputTip->闪退 这个问题在我的设备上是100%复现的。
> 
> 直接运行 `InputTip.exe` 软件本体试试呢？不运行快捷方式

经测试，如果直接运行软件本体（而非通过快捷方式指向的任务计划程序），的确可以正常启动。
发现是任务计划程序后，去检查了是否有注册成功，看到有一个“排队”中的计划任务；重启后，出现了一个没有触发器的计划任务。
![PixPin_20240925_001146](https://github.com/user-attachments/assets/1e34d9bd-a058-438d-a405-efb7b8ce00b2)

**Comment by abgox** [comment]
快捷方式就是通过任务计划程序实现的，这个计划任务本身不会有触发条件，只会在运行快捷方式的时候才触发
