### ISSUE TITLE
[Bug]: v2.14/v2.16 在第三方输入切换中英文模式会导致文本编辑软件崩溃

### ISSUE THREAD

**Issue by xuyisoso** [abgox/InputTip#22]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

在x64，win10，百度输入法6.1.12.0，打开notepad++或者obsidian编辑时候，如果使用百度输入法进行中英文切换会导致notepad++或者obsidian 崩溃，当然这个也可能时百度输入法的锅。不过使用微软拼音进行中英文切换就不会导致软件文本编辑崩溃。

### 期望结果

排查一下时inputTip的BUG还是百度输入法的BUG，不是inpuTip的bug就行

### 实际发生了什么?

[Bug]: v2.14/v2.16 在第三方输入切换中英文模式会导致文本编辑软件崩溃

**Comment by abgox** [comment]
- 我只能确认 Win 11 系统没有问题

![recording](https://github.com/user-attachments/assets/f64b7761-98b3-4cce-855d-d96bff5d17ba)

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可
