### ISSUE TITLE
[Bug]: InputTip2.16运行时，部分软件的安装程序执行过程中闪退（e.g. Notepad++）

### ISSUE THREAD

**Issue by zuilintan** [abgox/InputTip#23]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

后台运行InputTip，
启动[Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.7/npp.8.7.Installer.x64.exe)安装程序

### 期望结果

Notepad++安装程序正常执行

### 实际发生了什么?

![image](https://github.com/user-attachments/assets/7dd2e874-5bee-4702-8edc-9a0277ed61ff)
点击下一步卡住，
数秒后，闪退。

### 还有其他你想要补充的信息吗？

非常奇怪的Bug，开始我以为是我用了XMPII导致内存兼容的问题，
后来尝试将通知栏常驻的程序一个一个退出，才验证出居然是InputTip的问题。

此外，之前用Bandizip、7zip解压时，也概率复现（未验证，待复现后补充）。

**Comment by abgox** [comment]
那就奇怪了，我也是 Win11，我下载了这个安装程序，所有步骤，一切正常，安装完成

**Comment by zuilintan** [comment]
复现Gif：
![GIF 2024-9-20 15-33-57](https://github.com/user-attachments/assets/6632fa0f-488a-42a5-afea-9596bc4030bf)

**Comment by zuilintan** [comment]
奇怪，我这边是24H2
![QQ_1726817829294](https://github.com/user-attachments/assets/07a47462-9de2-4c0c-9583-4a8597fb5da6)

**Comment by abgox** [comment]
- 属实是除了我的电脑以外，谁的电脑都得来点奇奇怪怪的兼容性问题
![image](https://github.com/user-attachments/assets/364c578a-ba56-4fed-bb0c-d856b92a7212)
![demo](https://github.com/user-attachments/assets/d7f46145-6a2a-4872-8b1f-bf6b3cc288cd)

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可
