### ISSUE TITLE
[Bug]: 在油猴脚本中方块错位, 在钉钉在线文档中不显示方块

### ISSUE THREAD

**Issue by hhuimie** [abgox/InputTip#24]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

1. 油猴 方块错位
Chrome 版本 123.0.6312.123（正式版本） （64 位）
油猴 版本 5.2.0
新建脚本即可
![image](https://github.com/user-attachments/assets/f2a06c05-cdf8-4c99-903a-533d4ce7aa1f)

2. 钉钉在线文档 不显示方块
钉钉 版本 7.6.10
共享个excel文件即可
![image](https://github.com/user-attachments/assets/148d812d-bcfe-453c-ad89-121edd240273)

### 实际发生了什么?

如上bug复现

**Comment by SAMBILI** [comment]
download
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler

**Comment by abgox** [comment]
在浏览器中的错位，无法解决，因为浏览器中的光标位置信息都是由同一个获取光标位置的方法调用

**Comment by hhuimie** [comment]
钉钉聊天记录搜索框没有方块
![image](https://github.com/user-attachments/assets/93435ff0-66b2-457d-ba3d-994692decddd)

**Comment by abgox** [comment]
- Win 11 正常
![recording](https://github.com/user-attachments/assets/7c75cbe1-d5f4-4347-b8b7-d00cde3b2460)
