### ISSUE TITLE
[Bug]: OneCommander 中错误地自动删除了光标前内容

### ISSUE THREAD

**Issue by duanluan** [abgox/InputTip#25]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

重命名文件目录或点击地址栏

### 实际发生了什么?

升级 2.17 后出现的，会自动删除光标前内容
![20240920194429_rec_](https://github.com/user-attachments/assets/006f6305-3f16-4727-9921-e8be75b506ea)
退出重启 OneCommander、InputTip 后依旧如此，退出 InputTip 后正常

### 还有其他你想要补充的信息吗？

OneCommander v3.88

**Comment by abgox** [comment]
-  已经在 `2.17.1` 版本中修复
