### ISSUE TITLE
[Bug]: 按Ctrl+A全选文字会直接删除文字

### ISSUE THREAD

**Issue by chaylun** [abgox/InputTip#26]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

全选文字就行了
![PixPin_2024-09-20_21-30-21](https://github.com/user-attachments/assets/2f91a40b-2797-42b0-aa9a-9e3912950693)

### 实际发生了什么?

文字直接没了

### 还有其他你想要补充的信息吗？

之前一直用得好好的，现在突然出现问题了

**Comment by abgox** [comment]
- 已经在 `v2.17.2` 版本中修复

**Comment by chaylun** [comment]
更新太快了，👍
