### ISSUE TITLE
[Request]: 推荐提供下载的是一个含目录的压缩包，因为 exe 打开后会生成其他文件

### ISSUE THREAD

**Issue by duanluan** [abgox/InputTip#27]
### 描述这个功能请求

以免一些没那么熟练的人直接双击打开
我自己是在自己常用的软件目录（D:\ProgramFiles）新建了一个InputTip，把exe放进去运行的

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- README 中有写到这个
- 不过也还好，我也写了 `InputTip` 会生成哪些文件，其实也不多，也就一个文件夹和一个配置文件

![image](https://github.com/user-attachments/assets/1456f915-ba9e-450d-a414-9ca5b92c55e7)

**Comment by Faith-Mian** [comment]
> * README 中有写到这个
> * 不过也还好，我也写了 `InputTip` 会生成哪些文件，其实也不多，也就一个文件夹和一个配置文件

---

反馈一个不重要的小问题，关于系统盘权限控制，经测试在系统盘以管理员模式运行最新版inputtip主程序，只能生成配置文件，无法生成文件夹InputTipSymbol和InputTipCursor，所以报错如下。

> *#1 (499) : [Gui.Prototype.AddPicture] TipGuiPic := TipGui.AddPicture("w" picSymbolWidth " h" picSymbolHeight, "InputTipSymbol\default\CN.png")
*#1 (499) : [] TipGuiPic := TipGui.AddPicture("w" picSymbolWidth " h" picSymbolHeight, "InputTipSymbol\default\CN.png")
> Auto-execute

**Comment by abgox** [comment]
- 测试过了，我这里没有问题，只是当文件复制到系统盘中时，会有权限提示
- 能正常运行，正常生成文件夹
- 如果是 C盘根目录的话，我连 `InputTip.exe` 都没有办法复制过去，就别谈启动了

![image](https://github.com/user-attachments/assets/0b0c59f4-2008-4d9c-a2c7-46b43bd4d60b)

**Comment by abgox** [comment]
- 如果提供压缩包文件，当无法正常检测到更新，需要通过手动下载文件替换更新时，还需要从压缩包中解压出 `InputTip.exe` 进行替换
   - 实际压缩包里的其他内容对于更新的用户来说是无用的 
- 不如现在的一个 exe 单文件程序，直接替换这个单文件即可

**Comment by Faith-Mian** [comment]
结合昨天无法生成文件夹和今天自动更新失败的体验来看，可能问题在我的路径是c:\``\inputtip，软件无法定位特殊字符，所以新版被下载到roaming文件夹后，无法被移动到工作目录-_-

**Comment by abgox** [comment]
> 结合昨天无法生成文件夹和今天自动更新失败的体验来看，可能问题在我的路径是c:``\inputtip，软件无法定位特殊字符，所以新版被下载到roaming文件夹后，无法被移动到工作目录-_-

- 软件真的不建议直接放系统盘
- 万一软件有bug，直接影响到系统盘呢？
- 还是放在常规的一些地方比较好
- 比如: 
   -  `C:\Program Files`
   - `C:\Program Files (x86)`
   - 或者是其他盘符
