### ISSUE TITLE
[Bug]: QQ v9 自动输入内容

### ISSUE THREAD

**Issue by duanluan** [abgox/InputTip#28]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

点击 QQ 内的任意输入框，自动输入内容，内容不知道哪来的

### 实际发生了什么?

QQ 版本 9.7.23(29368)
在两台电脑上都出现了，第一台电脑重启 QQ 后消失，第二台电脑重启后无效
![20240920221828_rec_](https://github.com/user-attachments/assets/fe85fbd7-c47b-424c-813d-1b66f245053d)

**Comment by abgox** [comment]
- 已经在 `v2.17.3` 版本中修复
