### ISSUE TITLE
[Bug]: 在微信输入法设置常用语时不能正常输入

### ISSUE THREAD

**Issue by chaylun** [abgox/InputTip#29]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

![PixPin_2024-09-20_22-14-46](https://github.com/user-attachments/assets/ac92b328-f896-4671-b199-41e44f20b55a)
如图，输入“shang”会反着来，变成“gnahs”，而且光标也移动不了

### 期望结果

正常输入

### 实际发生了什么?

不能正常输入

### 还有其他你想要补充的信息吗？

无

**Comment by abgox** [comment]
- 微信输入法兼容不了，下个版本内部直接禁用了
- 毕竟也就也就只有一个输入常用语的场景

**Comment by abgox** [comment]
- 已经在 `v2.17.2` 版本中内部禁用
