### ISSUE TITLE
[Bug]: 小方块在资源管理器中不生效

### ISSUE THREAD

**Issue by zcyk** [abgox/InputTip#31]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

其他地方都能正常显示，只有资源管理器中不行，地址栏、搜索栏、重命名都不显示
win11家庭版
![屏幕截图 2024-09-21 082613](https://github.com/user-attachments/assets/8d6f81fd-ef3b-4af2-8cef-086ab5609020)
![屏幕截图_21-9-2024_82521_github com](https://github.com/user-attachments/assets/1a428c2b-8cc3-4ddf-b761-45ddfee03afc)

### 实际发生了什么?

如上复现

**Comment by abgox** [comment]
- 因为让文件管理器显示可能会催生出一些意外的bug，所以在之前的一个版本，直接将文件管理器默认添加到了隐藏列表中，且在当前版本中无法手动移除
- 可能过几个版本后会允许手动移除

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可
- 更新版本后，你需要在托盘菜单中的 `指定隐藏方块符号的应用` 中，把 `explorer.exe` 从其中移除
