### ISSUE TITLE
[Bug]: 在Windows 11记事本中会自动删除选中的文字

### ISSUE THREAD

**Issue by lbx1979** [abgox/InputTip#32]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

![PixPin_2024-09-21_09-45-51](https://github.com/user-attachments/assets/9d772cb1-2b34-4a3b-b31c-cb03d27910af)
记事本中选择文字会自动删除掉，并且没办法撤回

### 实际发生了什么?

记事本中选择文字会自动删除掉，并且没办法撤回

**Comment by abgox** [comment]
- 确定使用的最新版本 `2.17.4`，在最新版本中，是修复了的

**Comment by lbx1979** [comment]
2.17.4确实修复了，自动更新没有到最新版本，谢谢
