### ISSUE TITLE
[Bug]: 隐藏"英文"方块符号时出现Bug

### ISSUE THREAD

**Issue by 0xSa9** [abgox/InputTip#33]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

1.将英文状态方块符号颜色去掉,仅保留中文颜色
2.按快捷键-切换输入法时方块颜色不能按期望的逻辑显示
![itbug](https://github.com/user-attachments/assets/09e0ad0d-ecfc-41b7-b152-fa2646ade89a)

### 期望结果

去掉英文方块颜色后, 再切换输入法, 在切到中文状态时显示颜色方块,英文时什么也不显示

### 实际发生了什么?

切到中文状态,不显示颜色方块,打字时或从别的窗口重新切入就显示了
切到英文状态,却显示了个没有颜色的方块
(但方块设置中把中文颜色和英文颜色都保留,切换输入法时可以正常切换方块颜色,如Gif截屏所示)

### 还有其他你想要补充的信息吗？

已升级到了最新版本InputTips
方块边框样式为3
模式为2
输入法为:可可五笔(多多平台)

**Comment by abgox** [comment]
- 无法复现
![recording](https://github.com/user-attachments/assets/0b457709-a178-46ea-b451-88b421d42bc3)

**Comment by 0xSa9** [comment]
![image](https://github.com/user-attachments/assets/744d9d5d-653c-4e2b-8eb6-a9623cc93ee5)

我也重新试了下,如果"是否更改鼠标样式"设置为1,就如你录屏一样一切正常. 
但如果是0,就可以复现.

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可

**Comment by 0xSa9** [comment]
效率极高,软件好用,非常感谢
