### ISSUE TITLE
[Bug]: dbeaver社区版的sql编辑器中存在选中自动删除文字的问题

### ISSUE THREAD

**Issue by lbx1979** [abgox/InputTip#34]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 当前使用的 InputTip 版本

2.17.4

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

![PixPin_2024-09-21_11-52-18](https://github.com/user-attachments/assets/921a8e19-07ee-4e0b-b8d1-87cebf43b450)
DBeaver版本是24.1.0

### 实际发生了什么?

dbeaver社区版的sql编辑器中存在选中自动删除文字的问题

**Comment by abgox** [comment]
DBeaver 是 64位的还是32位的

**Comment by lbx1979** [comment]
> DBeaver 是 64位的还是32位的

64位

**Comment by abgox** [comment]
- 已经在新版本 `v2.17.5` 中修复
- 重启更新版本即可
