### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by czz404** [abgox/InputTip#35]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 当前使用的 InputTip 版本

2.17.4

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

acrobat dc pro 最新版（版本 2024.003.20112），打开文件后点击注释，再点击右侧栏的添加注释，会自动输入字母（在此前的 InputTip 版本中也有类似情况

![pic_1726906037.png](https://s2.loli.net/2024/09/21/ngVXiIYoAUNqMvy.png)

### 期望结果

正常输入文字

### 实际发生了什么?

自动输入字母

### 还有其他你想要补充的信息吗？
输入法是微信输入法，模式二
如果大佬没有 Acrobat 无法进行测试不修复也没关系，已经添加到隐藏里了，没啥影响

**Comment by abgox** [comment]
- 最新版本是 `2.17.5`
- 重启更新即可，如果重启没有更新，在 Release 中手动下载
![image](https://github.com/user-attachments/assets/af60ae88-937e-4451-b78d-f1f4a09c38be)

**Comment by czz404** [comment]
好的，抱歉没看清楚版本号，新版可以了
