### ISSUE TITLE
[Bug]: 指定应用隐藏方块符号避免应用崩溃

### ISSUE THREAD

**Issue by Faith-Mian** [abgox/InputTip#36]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 当前使用的 InputTip 版本

2.17.6

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

方块符号闪退可以通过隐藏解决，但还是想描述一下具体情况，不知道有没有解决的。

在anlink这款scrcpy类多屏协同软件中，无论尝试哪种输入法模式，只要一开【显示方块符号】就非常不稳定。

### 实际发生了什么?

接下来在文本框点击小方块或者切换输入法就会让anlink崩溃退出，再次打开依然会数秒内闪退，但inputtip功能一切正常。

### 还有其他你想要补充的信息吗？

补充一下另一位ahk爱好者的"输入状态跟随”，作用是让原本固定在屏幕上的输入法提示框一直跟随鼠标移动以提示当前输入法状态。这里是他的帖子和源码直链，不知道inputtip有没有兴趣合并它作为一种模式。

> https://meta.appinn.net/t/topic/31987
> http://ys-g.ysepan.com/621015427/916128327/SVujfIs485J2J4N22QNL47/%E8%BE%93%E5%85%A5%E7%8A%B6%E6%80%81%E8%B7%9F%E9%9A%8F.ahk?lx=xz

### 补充

【更改配置】- 【鼠标样式配置】- 【设置中文/英文/大写鼠标样式】- 弹出选择对话框后点击选择或取消 - 对话框和更改配置窗口均关闭

这里有必要改成回到【更改配置】吗？

**Comment by abgox** [comment]
- 有些应用崩溃我也没有太多的办法，毕竟通用的获取光标位置的方法，大部分应用不崩溃，少部分应用崩溃，这就不是方法的问题，是兼容的问题，只能尽力兼容
- 暂时的方法就是隐藏，等待兼容(如果有办法兼容的话)

**Comment by abgox** [comment]
- 实测，在 WIn11 中不会崩溃，不过也无效，获取不到光标位置
- 在下个版本中直接内部禁用了

**Comment by abgox** [comment]
- 已经在 `2.18.0` 版本中内部禁用 anlink


> 【更改配置】- 【鼠标样式配置】- 【设置中文/英文/大写鼠标样式】- 弹出选择对话框后点击选择或取消 - 对话框和更改配置窗口均关闭

- 已完善，现在 `更改配置` 窗口不会再关闭，除非点击 `确定` 或者 `x`

**Comment by Faith-Mian** [comment]
> * 已经在 `2.18.0` 版本中内部禁用 anlink

发现Inno Setup打包的安装程序也有闪退问题，ahk_class是TWizardForm
