### ISSUE TITLE
[Bug]: WIN10系统,在系统应用"画图",点击输入文字,打字的时候会导致无限重复.

### ISSUE THREAD

**Issue by only4freedom** [abgox/InputTip#38]
### 开始之前...

- [X] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 当前使用的 InputTip 版本

2.15.0

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

![image](https://github.com/user-attachments/assets/0018d1cf-78a5-4535-9ac2-f14d5f6d28d3)
只需要打开画图,然后点击文本输入,随便按一个字符,此时字符会无限重复.

### 实际发生了什么?

打开画图,然后点击文本输入,随便按一个字符,此时字符会无限重复.

**Comment by abgox** [comment]
- 哥们，你使用的不是最新版本啊，最新版本当前是 `2.17.6`
  - 先使用最新版本，如果还有问题，再重启这个 issue
- 我设置的这些需要勾选的复现框，你们真的看了吗

![image](https://github.com/user-attachments/assets/eb01b274-45c3-49d6-b0de-1df85894cc79)

**Comment by only4freedom** [comment]
我以为退出重进就更新,结果一直没更新.手动从release中下载最新版后没问题了. 测试画图中不会再无限重复了.

**Comment by abgox** [comment]
- 有时候也可能存在网络环境访问新版本失败，就没有检查到更新，最好多试几次
- 如果都不行，就在项目 Release 中下载最新版本
