### ISSUE TITLE
[Bug]: 在Firefox浏览器任意搜索框均不显示方块

### ISSUE THREAD

**Issue by TheWiseWolfHolo** [abgox/InputTip#39]
### 开始之前...

- [x] 你正在使用 InputTip 的最新版本。
- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了相关问题。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/)

### 当前使用的 InputTip 版本

2.17.6

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

- 更新2.17.6后，Firefox不显示方块，重启也无用

### 实际发生了什么?

![图片](https://github.com/user-attachments/assets/22646eac-cb64-4907-9624-679f9a263f07)
![图片](https://github.com/user-attachments/assets/ac54494b-65c0-4660-af9b-243c5700d43f)

### 还有其他你想要补充的信息吗？

相对应地，edge，Chrome均显示正常，隐藏应用列表也为默认设置并未更改，尝试删除重新下载安装仍是如此。
Fig1 edge
![图片](https://github.com/user-attachments/assets/13768cc0-9f74-4ace-8dcf-f8ea2dad2bbc)
Fig2 Chrome
![图片](https://github.com/user-attachments/assets/cf891d66-516d-43c2-a600-b810378874e5)

**Comment by abgox** [comment]
- 已经在新版本 `v2.18.1` 中修复
- 重启更新版本即可
   - 如果重启没有检查到更新，直接下项目 Release 中下载最新版本
