### ISSUE TITLE
[Bug]: 哥，能不能不要加个思路就更新一版，或者弄个开发版可以么？谢谢

### ISSUE THREAD

**Issue by Jimokov** [abgox/InputTip#41]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.184

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

频繁更新

### 期望结果

出开发版

### 实际发生了什么?

![PixPin_2024-09-22_09-16-32](https://github.com/user-attachments/assets/2688415e-d1d8-425f-a2ba-50b0021b3fdf)
![PixPin_2024-09-22_09-17-22](https://github.com/user-attachments/assets/7007b339-087c-46ef-a1df-8666283407d1)

软件非常好，好就好在它和其它相类似软件一样，没有花里胡哨的功能，就安安静静的在那里

但现在一天一版，给人感觉加个功能，改个设置就更一版，现在菜单越来越繁复，眼花缭乱

最关键的，更新的时候能不能不要强制更改用户已经设置好使用习惯？或者可否有个导出设置？

第一天用，上来先改了我的鼠标样式，我找了半天怎么改回去，差点放弃这个软件，后来发现可以使用自己的鼠标样式

今天用的好好的方块，上来就变成一个红点，这个红点还不叫红点，叫什么图片样式

原来的方块是紧随光标的，现在的红点离着光标“八丈远”，我不知道能不能设置，但是为啥要改变原来用户已经设置好的

强制更改默认使用环境？

太乱了

我知道您免费做这个软件，每天更新，我不应该这么吐槽

但是如果可以的能不能弄个开发版或者测试版啥的，天更遭不住啊！

-------------------------------------------

菜单简单明了三大类别，别一直横向加标签，可以纵向加标签么

![PixPin_2024-09-22_09-50-09](https://github.com/user-attachments/assets/34596b0b-c038-4626-802a-a09926adbc0d)

**Comment by Jimokov** [comment]
> 关于频繁更新，我觉得是好事，可以快速修复bug，更新迭代。建议作者在确认按钮边上加个选项： 忽略新版本更新提示。这样以后就不自动检查更新，除非重新开启自动检查更新。
> 
> 目前的设置UI很简洁，很专业，希望保持。

![PixPin_2024-09-22_12-47-18](https://github.com/user-attachments/assets/6a342350-a227-4eb0-8e30-0f96dc6c297c)

这样重复的UI设置算简洁么

**Comment by zhigang-he** [comment]
今天发现软件又更新之后特意上 github issue 来看有没有人提这个意见。我完全赞同题主，用这个小工具就是因为经常在敲字以后才发现输入法状态不对，来回切换觉得麻烦。开发者确实解决了一个真实存在的问题，哪怕这个问题看起来很小。这就很好，我甚至愿意为它付费，但前提是它能安安静静干活，现在这样隔天一个版本，比输入法存在感还强，还不能不更新，实在是受不了。希望开发者能像题主建议的那样，好歹先弄个稳定点的测试版，起码消停一段时间。

**Comment by zhigang-he** [comment]
说到底就是一个提示的功能，长条也好，圆点也好，方块也好，其实啥都行，用惯了就顺眼了，真没必要搞那么复杂

**Comment by abgox** [comment]
- 需求已理解，下个版本，添加忽略检查更新的选项
---
- 对于配置菜单，因为我想保持软件在这方面更简洁一点，完全使用 AHK 最基本的 GUi 来做的，它还不支持正常的缩放，目前这样勉强是个能用的方案
-  至于为什么要有下面这么多个，因为有的人的屏幕高度很低，我只能尽量让每一个配置页面的高度低一点，所以拆成了多个
   - 如果弄成竖排的话，高度太过了，在有的屏幕低的用户那里就无法显示完全，得等我先解决 Gui 的缩放问题
   - 不过它应该是显示在一排的，为什么在你那里显示成了两排，可能是个bug

![image](https://github.com/user-attachments/assets/fe52e9b9-cae8-459b-b9c3-a46495ed5994)

---
- 对于频繁更新，我一直觉得现在的更新方式已经非常简单，显示个弹窗，点个确定，不需要再做其他的事
- 频繁更新，现在更多的是对部分软件兼容的更新，在 Windows 平台，许多软件是没法统一的，只能一对一的兼容
- 就像前面在某个版本之前，在 Firefox 浏览器中，是不支持的， 所以我快速发了新版本，只是希望能减少用户使用时的问题
- 后续，只要兼容了一个软件，应该还是会立马更一个新版本，不过有 `忽略检查更新` 的选项，用户可以通过它减少弹窗干扰

**Comment by abgox** [comment]
- 关于配置
- 所有的配置都是存储在 `InputTip.ini` 中，我只强行给用户添加过一次
  -  `Taskmgr.exe` `explorer.exe` `StartMenuExperienceHost.exe` 这三个应用经过反馈，大概率会导致问题，许多用户自己又不知道怎么弄，我就强行给所有用户将它们添加为了 `隐藏符号的应用`
- 除此以外，软件更新没有覆盖过用户的配置
- 只是，`图片符号` 有更高的优先级，当 `是否显示图片符号` 为 `1` 时，就会直接改为图片符号
- 且，我将它的默认值设置为了 `1`，确实相当于让所有用户强制更改为了图片符号
---
- 为什么这么做？
- 首先，图片符号，自定义能力更强，你可以随意替换图片，即使不替换，默认的这三个圆点，对于大部分用户来说，应该是比以前的方块符号好看的
- 因为反馈中，我知道，大部分用户不会去更改配置
- 而能够来这里开 issue 的，一定会修改配置
- 如果喜欢以前的方块，将 `是否显示图片符号` 改为 `0` 即可  
   - 这个我是在更新日志中特别提到了的

**Comment by abgox** [comment]
- 已经在新版本(`v2.19.0`)中的托盘菜单中添加了 `忽略更新`
- 同时，当有更新弹窗时，在更新弹窗底部也添加一个 `忽略更新` 按钮

**Comment by abgox** [comment]
> 说到底就是一个提示的功能，长条也好，圆点也好，方块也好，其实啥都行，用惯了就顺眼了，真没必要搞那么复杂

- 有的用户反馈，方块太丑了...
- 所以才弄了个图片符号，这样觉得丑的就可以自己替换自己觉得好看的图片了
