### ISSUE TITLE
[Bug]: 软件exe双击后被Symantec Endpoint Protection隔离

### ISSUE THREAD

**Issue by kai06** [abgox/InputTip#42]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

<img width="762" alt="quarantine" src="https://github.com/user-attachments/assets/15ed3f7f-9b82-4ce5-b1f3-e303621ca2fd">
软件运行后被Symantec隔离。

### 实际发生了什么?

被隔离，被提示：
Category: Insight Network Threat
Sub Category: Insight Network Threat
Status: Infected

**Comment by abgox** [comment]
- 基于 AutoHotkey 开发的软件被误认为是病毒，挺正常的事情
- `InputTip` 完全是开源项目，源代码人人都可见的
- 如果你认为它有病毒，就别用，如果认为没有病毒，就自行解决这些病毒检测软件的隔离手段

**Comment by kai06** [comment]
应是赛门铁克基于组策略报的，我没有权限能够解除隔离。
诚心请教，我是否可以直接安装AHK，用AHK脚本方式运行它？

**Comment by abgox** [comment]
- 那你需要 clone 这个仓库，下载 AutoHotkey 之后，运行仓库中的 `InputTip.ahk`
- 一定要在托盘菜单中勾选 `忽略更新`，因为更新是直接下载 `InputTip.exe`,依然会被隔离
- 想要更新的话，就重新 pull 这个项目的源代码
- 不过直接运行 `InputTip.ahk` 会导致没有管理员权限，可能许多环境中，会由于没有权限无法生效
- 你需要将 AutoHotkey 设置为以管理员权限运行

**Comment by kai06** [comment]
谢谢，我按照这个说明试试看。

**Comment by abgox** [comment]
- 这就没有办法了，我是基于 AHK 2.1 alpha 版本开发的，使用了一些 alpha 版本的语法
- 所以 AHK 2.0 版本直接运行 ahk 文件是运行不了的

**Comment by abgox** [comment]
- `2.21.7` 版本，已经将 `AutoHotkey` 版本从 `2.1-alpha` 退回到 `2.0`
- 只要 AutohotKey v2.0 在你的电脑上不会被隔离，就可以克隆这个项目直接运行 `InputTip.ahk` 了
- 注意: 直接运行 `InputTip.ahk` 的方式，生成的 `InputTip.lnk` 快捷方式是不可用的

**Comment by kai06** [comment]
下载的2.21.9用AHK2.0运行，目前工作良好。

AHK 2.0可能安装文件获得了微软签名，AHK 2.1 Alpha版本可能还没正式签名导致。之前的 InputITip.exe不确定是否也是因为这个原因被赛门铁克误杀。

感谢更新！

**Comment by abgox** [comment]
> 下载的2.21.9用AHK2.0运行，目前工作良好。
> 
> AHK 2.0可能安装文件获得了微软签名，AHK 2.1 Alpha版本可能还没正式签名导致。之前的 InputITip.exe不确定是否也是因为这个原因被赛门铁克误杀。
> 
> 感谢更新！

- 再次提醒，通过直接运行 `InputTip.ahk` 的方式，如果 `AutoHotkey` 没有设置为管理员权限，`InputTip` 就没有管理员权限，在一些有管理员权限的软件窗口中会失效的
- 如果遇到，你就需要去尝试让 `AutoHotkey` 以管理员权限启动了
- 当前，你最好重新使用 `git pull` 拉取一下最新的项目仓库代码，重新运行 `InputTip.ahk`
- 因为最新版本 `2.21.10`，应该解决了大部分潜在的兼容性问题
