### ISSUE TITLE
[Request]: 使用计划任务执行开机自启动

### ISSUE THREAD

**Issue by NEANC** [abgox/InputTip#43]
### 描述这个功能请求

- 当前，在用户未取消 用户账号控制程序（UAC）/ 关闭打开程序的“安全警告" 时，软件自启动会在每次启动/注销后会系统 自动弹出 UAC确认窗口，这会造成一定的困扰。
- 解决方案：可以使用计划任务执行自启动来避免这个问题
    - 使用 schtasks 命令 - CMD
        - 不建议使用，原因：无法处理电源参数，可能会导致笔记本用户无法运行
    - 使用 New-ScheduledTask 命令 - PowerShell

## 例
schtasks 命令
```cmd
schtasks /create /tn "InputTip (Run As Admin)" /tr X:\InputTip\InputTip.exe /sc ONLOGON /rl HIGHEST /F
```

参考资料：
https://learn.microsoft.com/zh-cn/windows/win32/taskschd/schtasks
https://learn.microsoft.com/zh-cn/windows-server/administration/windows-commands/schtasks-change

------

New-ScheduledTask 命令有些复杂，无法提供例（
~~实在是啃不动了 :joy: （~~
https://ss64.com/ps/new-scheduledjoboption.html
https://learn.microsoft.com/zh-tw/powershell/module/scheduledtasks/new-scheduledtask

### 你正在使用什么 Windows 系统版本?

Windows 11, Windows 10

**Comment by abgox** [comment]
- 这个问题正好已经在刚刚发布的 `v2.21.0` 新版本中解决
- 当启动 `InputTip.exe` 时，需要管理员权限，这是毫无疑问的，但是启动后，会生成一个 `InputTip.lnk` 快捷方式
- 这个快捷方式有点特殊，使用它去启动 `InputTip.exe`  就不会有 `UAC` 权限提示窗口了

**Comment by NEANC** [comment]
肝帝 :thumbsup: :thumbsup: :thumbsup:
