### ISSUE TITLE
[Bug]: 图片符号锯齿严重?

### ISSUE THREAD

**Issue by hhuimie** [abgox/InputTip#44]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.0

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

![image](https://github.com/user-attachments/assets/5d2eec6c-3fc7-4a7c-9f66-ee120a3256be)

### 实际发生了什么?

![image](https://github.com/user-attachments/assets/4a8317be-691c-4893-a7d4-df459cfcc3ae)
我一开始以为是分辨率问题, 但是即使把图片符号高度宽度设置成30, 和另一个软件的圆形对比还是相差很多
![image](https://github.com/user-attachments/assets/1e16b680-a747-44a7-94c6-b02a81745094)
![image](https://github.com/user-attachments/assets/ecedc00d-bca8-4051-9411-b909f65b2d84)

**Comment by abgox** [comment]
![image](https://github.com/user-attachments/assets/51c33c80-31eb-4cd1-bd44-deec2bc6a9e1)
- 使用图片，自定义程度高，可以自己随意换，但同时也会存在这种锯齿问题，还很难解决
- 在我的电脑上，2560 x 1440 的屏幕，175% 的缩放率，看着还行
- 如果看不习惯，还是换回方块符号或文本字符吧
