### ISSUE TITLE
[Bug]: wps 方块错位?

### ISSUE THREAD

**Issue by hhuimie** [abgox/InputTip#45]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.0

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

![image](https://github.com/user-attachments/assets/788cb822-e700-4c57-a632-019bb2de686a)

### 实际发生了什么?

正常显示如下
![image](https://github.com/user-attachments/assets/a568549b-8c75-4953-a5e9-53cac4456654)

wps如下
![image](https://github.com/user-attachments/assets/ab29e8ae-db8f-4015-8233-3c8b2b5fa42f)
![image](https://github.com/user-attachments/assets/ab53b608-5ca7-4984-a457-db74270afa3a)

office没发现这问题
方块和图片好像都有这问题

**Comment by hhuimie** [comment]
微信好像也是, 微信在2.17.0好像没问题
![image](https://github.com/user-attachments/assets/bc556c6e-5c98-410c-8918-eafa836256bf)

**Comment by abgox** [comment]
确实有问题，等我测试一下

**Comment by abgox** [comment]
- `v2.21.1` 版本中已修复

**Comment by hhuimie** [comment]
我这边wps还是不行, 版本11.8.2.8411

**Comment by abgox** [comment]
- 在目前所有的获取光标的位置方法中，wps都无法准确的获取到位置，没有办法
- 下个版本，我直接把 wps 禁掉了
