### ISSUE TITLE
自定义边框样式不能正常显示[Bug]: 

### ISSUE THREAD

**Issue by zittr** [abgox/InputTip#47]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.1

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

更改方框符号边框时，如果开启了字符显示，自定义边框样式会失效，而内置的三个样式却能正常显示。

### 期望结果

开启字符显示的方框，自定义边框样式，会和三个内置的样式一样，能正常显示。

### 实际发生了什么?

更改方框符号边框时，如果开启了字符显示，自定义边框样式会失效

**Comment by abgox** [comment]
- 如果使用文本字符的话，在渲染上会存在问题，没有办法达到视觉上 `边框`  的效果
- 更建议使用内置的三种样式，如果觉得不好看，你可以直接使用图片符号，你可以做三张类似效果的图片替换默认的图片
