### ISSUE TITLE
[Bug]: 自动更新卡巴斯基报毒

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [abgox/InputTip#48]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.0-2.21.1

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

检测到更新并选择下载更新。随后卡巴斯基报毒并删除程序。
检测到对象：PDM:Trojan.Win32.Generic
检测方式：行为分析

### 期望结果

正常更新

### 实际发生了什么?

卡巴斯基报毒并自动删除

### 还有其他你想要补充的信息吗？

把病毒检测结果贴上来并建议用户自己添加排除列表，卡巴误杀挺多的，只有更新时行为检测报毒我认为是误杀
手动替换文件没问题

**Comment by abgox** [comment]
- 手动替换文件没问题就行了
- 报毒这种，我解决不了，只能用户自行解决

**Comment by lingfengyu-dreaming** [comment]
![PixPin_2024-09-23_11-44-03](https://github.com/user-attachments/assets/844a2217-9bbe-41e7-acea-19365e941219)
我重新下载完文件之后图片会随着打字由大变小循环显示是bug吧，1.21.1出现的

**Comment by abgox** [comment]
- 什么场景中打字？
- 我也是Win11，但是我这里没有这个问题，无法复现

**Comment by lingfengyu-dreaming** [comment]
就是directory opus和edge，给电脑都搞卡了，几乎无响应，刚才超时自动隐藏之后又彻底不显示了，我重装一下试试

**Comment by lingfengyu-dreaming** [comment]
重装问题还是存在，并且超时后还在输入中就自动隐藏，我重启电脑试试，可能还是跟卡巴斯基有关

**Comment by abgox** [comment]
卡巴斯基 这到底是个什么东西？听都没听过

**Comment by lingfengyu-dreaming** [comment]
重启解决问题，卡巴斯基是国外的杀毒软件，查杀能力算好的

**Comment by abgox** [comment]
好吧

**Comment by lingfengyu-dreaming** [comment]
有可能是实现自动更新的方式是下载文件后替换本体，实现方式太像病毒导致误报，另外，排查出图片显示异常可能跟超时隐藏有关，在隐藏之后再次显示出来就会出现图片由大到小切换的问题，超时时间是10秒，位置是水平偏移0，垂直偏移-25

**Comment by abgox** [comment]
> 超时时间是10秒，位置是水平偏移0，垂直偏移-25
- 这样设置测试了，在我电脑上，仍然一切正常，无法复现问题

**Comment by lingfengyu-dreaming** [comment]
![PixPin_2024-09-23_12-35-33](https://github.com/user-attachments/assets/544f210b-f6b0-481b-aacf-e65cd28fdddd)
![PixPin_2024-09-23_12-35-49](https://github.com/user-attachments/assets/8eef4259-f74d-41c2-adab-b6bfd4a87bf0)
![PixPin_2024-09-23_12-36-09](https://github.com/user-attachments/assets/47c5b601-1b62-45d5-89da-763faf1432ef)
我倒是稳定复现但是不知道问题在哪，设置了微信默认中文，开机自启，其他统统默认没改

**Comment by lingfengyu-dreaming** [comment]
图片还是没排查出来，我把其他可能影响的应用都排查一遍了，只有图片会错误显示。
编辑：切成方块之后再切回来又一时半会没有复现，是不是单纯图片显示的代码有哪里调用不全面需要正确初始化一下

**Comment by lingfengyu-dreaming** [comment]
还是复现了，就是有问题，排查不来

**Comment by lingfengyu-dreaming** [comment]
图片异常显示的问题移到 #49 讨论，卡巴斯基报毒问题应该由用户添加排除项解决。
