### ISSUE TITLE
[Bug]: 图片符号大小异常自动切换

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [abgox/InputTip#49]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.3

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

使用图片符号，设置超时时间，待超时自动隐藏之后重新按键，显示图片后若图片大小与设置大小不符（通常为首先变小，随后按键或切换窗口继续变小，最小后立即变成最大，之后循环），即复现

### 期望结果

重新显示正确大小图片

### 实际发生了什么?

https://github.com/user-attachments/assets/d1da61af-2baf-4104-b758-853cecdaa6d9

图片大小切换循环显示

### 还有其他你想要补充的信息吗？

_Originally posted by @lingfengyu-dreaming in https://github.com/abgox/InputTip/issues/48#issuecomment-2367181401_

**Comment by abgox** [comment]
- 和你完全一模一样的配置，系统环境也是相同的 Win11，我依旧复现不了你的问题
- 那就应该不是 `InputTip` 的问题
- 你的录屏里，那一排的软件，全都关了试试？
![recording](https://github.com/user-attachments/assets/e094d7c8-5e24-4647-80a1-32ded22e08a3)

**Comment by lingfengyu-dreaming** [comment]
我全部关了测试还会，输入法是微软拼音输入法，在配置界面快速连续切换输入框加上输入文本又复现了，在复现时聚焦到输入框时没有出现图片，而是出现了一个透明窗口，只能看见左边框和下边框，大小可以装下最大的图片，应该是软件的上层显示窗口。视频里没有体现，但是我可以实际观测到这个窗口出现一瞬间，然后就出错了

**Comment by lingfengyu-dreaming** [comment]
这个问题时有时没有，只有我自己能复现，我就当是我的环境内有应用冲突，不是软件问题，关了吧

**Comment by lingfengyu-dreaming** [comment]
有办法获取程序的日志输出或者类似功能的记录吗，要是有我就复现试试，现在不用图片显示了

**Comment by lingfengyu-dreaming** [comment]
我仔细查了一遍也没发现哪里有问题，不能是我本地装了低版本ahk的原因吧

**Comment by abgox** [comment]
后面看吧，如果不复杂的话，我尝试一下，不再使用 AHK 2.1 alpha 版本，退回 AHK 2.0

**Comment by lingfengyu-dreaming** [comment]
我让GitHub copilot看过了，没说有报错，可能就是Windows改了api，ahk没有及时跟进，如果真改了估计是需要下放到正式版才会跟进微软，改函数挺麻烦的，不少函数用了2.1的特性写法，建议放着，能用就行

**Comment by abgox** [comment]
主要我使用 2.1 只是图方便，因为 2.1 可以直接使用匿名函数，其他特性我倒没有用啥，退版本应该也不难

**Comment by abgox** [comment]
- `2.21.7` 版本，已经将 `AutoHotkey` 版本从 `2.1-alpha` 退回到 `2.0`
