### ISSUE TITLE
[Bug]: 在skylark文本编辑器中输入英文方块符号不跟随

### ISSUE THREAD

**Issue by czz404** [abgox/InputTip#50]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.3

### 你正在使用什么 Windows 系统版本?

Windows 11

### bug 复现步骤

![test](https://github.com/user-attachments/assets/7a1e19f5-262c-4ce8-8cef-4ed6fab4a59e)

skylark：https://github.com/adonais/skylark

### 实际发生了什么?

中文输入跟随正常，英文/大写不跟随

**Comment by abgox** [comment]
- 实测了，如果使用 x86版本会有不跟随的情况，如果使用 x64版本就没有问题了
- `2.21.4` 版本中，修复 x86 版本的问题
