### ISSUE TITLE
[Bug]: 启动报错,应该是不支持低版本的windows

### ISSUE THREAD

**Issue by songxff** [abgox/InputTip#51]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.4

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

![image](https://github.com/user-attachments/assets/8b5db398-9967-441c-9bc7-473129dcaabe)
![image](https://github.com/user-attachments/assets/7318d0a4-d563-474a-b851-834990d23303)
![image](https://github.com/user-attachments/assets/52307d65-12f2-4e01-bd11-2bcc3c33af86)
应该是不支持我当前的windows版本

### 期望结果

正常启动

### 实际发生了什么?

无法启动

**Comment by abgox** [comment]
- `2.21.5` 版本中抑制了这个错误
- 这个 Dll 调用主要是解决在副屏幕上的坐标偏差
- 如果低版本电脑不支持的话，在副屏幕上就会有问题，不过主屏幕中没有影响
