### ISSUE TITLE
[Bug]: pandanoCR文本窗口疯狂自动复制输入的内容

### ISSUE THREAD

**Issue by lhj5426** [abgox/InputTip#53]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2.21.8

### 你正在使用什么 Windows 系统版本?

Windows 10

### bug 复现步骤

https://github.com/user-attachments/assets/a477c162-2ddc-42eb-a5d3-fb5e8ecb5dfc

如视频所示 在pandanOCR里输入完文字之后启动 您的软件 就会自动疯狂增值自动重复

### 期望结果

可以修正

### 实际发生了什么?

在上面说了

### 还有其他你想要补充的信息吗？

暂时没了

**Comment by abgox** [comment]
> 在有些软件中仍然会自动复制输入，比如LESLIE NOTE.

- `2.21.10` 版本尝试恢复
- 如果还有问题，请提交 issue
