### ISSUE TITLE
[Request]: 请求添加对windows11系统窗口支持

### ISSUE THREAD

**Issue by hfj8210** [abgox/InputTip#54]
### 描述这个功能请求

请求添加对windows11系统窗口支持，比如搜索框，资源管理器路径栏，修改文件名，OneNote.....

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- OneNote 已支持，Office 全家桶都支持
- 资源管理器可能在 Win10有兼容性问题，不过Win11应该没啥问题
   - 点击 `托盘菜单` => `指定隐藏符号的应用` ，将其中的 `explorer.exe` 移除即可
 - 系统窗口无法支持，有可能导致崩溃，很多时候也获取不到准确的输入法状态
