### ISSUE TITLE
[Bug]: google搜索框无法快速选择文字

### ISSUE THREAD

**Issue by gbsix** [abgox/InputTip#55]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.9

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

浏览器，Google搜索输入框

### bug 复现步骤

使用英文Google输入关键词搜索，然后修改搜索词，从右往左快速选择文字，光标会自动跳转到文字最后

### 期望结果

希望这个下工具在任何时候都不影响输入内容

### 实际发生了什么?

光标会自动跳转到文字最后，选择的内容被强制取消

![IMG_20240924_104555](https://github.com/user-attachments/assets/4e8683d4-898a-4ad2-a4c2-77a766126840)

**Comment by abgox** [comment]
- Chrome 浏览器吗
- 测试正常，没有复现这个问题

**Comment by abgox** [comment]
- `2.21.10` 版本尝试修复
- 如果问题仍然存在，请重开这个 issue
