### ISSUE TITLE
[Bug]: Outlook 365界面，方块符号行为异常

### ISSUE THREAD

**Issue by kai06** [abgox/InputTip#56]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2 (AHK 2.0)

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

Microsoft Outlook

### bug 复现步骤

Microsoft Outlook (365) ：

1. 撰写邮件内容界面，方块符号不出现。
2. 撰写邮件地址栏方块符号正常。（见图）

Microsoft Outlook (365)：
阅读界面，选中邮件后，方块符号会根据鼠标位置（靠左和靠右）出现在两个地方（见图）

截图：
![outlook阅读界面-方块出现-靠右](https://github.com/user-attachments/assets/566bc146-d527-40d7-8607-27689b90458b)
![outlook阅读界面-方块出现-靠左](https://github.com/user-attachments/assets/077cd32d-bdd8-4c41-be3f-56c529d7bd76)
![outlook内容撰写界面-方块不出现](https://github.com/user-attachments/assets/abc03979-538a-48ef-90c9-58ee7dc59662)

### 期望结果

撰写邮件内容界面，方块符号应出现。
阅读界面，方块应不出现。

### 实际发生了什么?

请参见截图

### 还有其他你想要补充的信息吗？

Outlook版本：Microsoft® Outlook® for Microsoft 365 MSO (Version 2402 Build 16.0.17328.20550) 64-bit 
直接运行的AHK 脚本。

**Comment by abgox** [comment]
- 无法复现这个问题
- 我也是 Win11，测试了 Outlook，有时候检测不到光标时，可能会显示在屏幕左上角位置，但不会显示在截图所示位置
- 显示在左上角，不影响体验，也就无所谓了
- 或者你可以设置自动隐藏，这样应该能提升体验
