### ISSUE TITLE
[Bug]: 启用InputTip后（AHK脚本方式启动），点击Outlook 地址栏，人名会被删除

### ISSUE THREAD

**Issue by kai06** [abgox/InputTip#57]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2 (AHK 2.0方式启动)

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

Microsoft Outlook

### bug 复现步骤

启用InputTip后（AHK脚本方式启动），点击Outlook 地址栏的人名；或者选中后拖动地址栏人名，人名会被删除。

### 期望结果

不应删除文字/字符。

### 实际发生了什么?

人名会被删除。退出InputTip后，行为正常了。

### 还有其他你想要补充的信息吗？

如果更改配置："不显示符号”，就没有删除文字的人名的问题了。

**Comment by hfj8210** [comment]
不光是点击Outlook 一个软件，用v2rayN编辑服务器时，本想拖动选中文本，可文本会被删除

**Comment by kai06** [comment]
Update: 如果更改配置："不显示符号”，就没有删除文字的人名的问题了。

**Comment by abgox** [comment]
- Win11，outlook，无法复现问题

![recording](https://github.com/user-attachments/assets/be07c0b9-96f0-4763-ac82-f546fb9c47e9)

**Comment by abgox** [comment]
> 不光是点击Outlook 一个软件，用v2rayN编辑服务器时，本想拖动选中文本，可文本会被删除

- 单独提交 issue，附带 bug 复现步骤

**Comment by kai06** [comment]
> * Win11，outlook，无法复现问题
> 
> ![recording](https://private-user-images.githubusercontent.com/131574323/370179080-be07c0b9-96f0-4763-ac82-f546fb9c47e9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjY5NTIsIm5iZiI6MTcyNzE2NjY1MiwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwMTc5MDgwLWJlMDdjMGI5LTk2ZjAtNDc2My1hYzgyLWY1NDZmYjljNDdlOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIwYWQ5OTQ3NTFmYzNlNDQ4OTllN2RmMGFjYzI1Yjc2NzVlZDliNzFkMGRmMDUxMGUzZmM3ZmEzOGVlYzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q3ruS9yGDt13drtE9_NCEkwfzzcr4nZth1yXIgXS9IA) [ ![recording](https://private-user-images.githubusercontent.com/131574323/370179080-be07c0b9-96f0-4763-ac82-f546fb9c47e9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjY5NTIsIm5iZiI6MTcyNzE2NjY1MiwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwMTc5MDgwLWJlMDdjMGI5LTk2ZjAtNDc2My1hYzgyLWY1NDZmYjljNDdlOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIwYWQ5OTQ3NTFmYzNlNDQ4OTllN2RmMGFjYzI1Yjc2NzVlZDliNzFkMGRmMDUxMGUzZmM3ZmEzOGVlYzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q3ruS9yGDt13drtE9_NCEkwfzzcr4nZth1yXIgXS9IA) ](https://private-user-images.githubusercontent.com/131574323/370179080-be07c0b9-96f0-4763-ac82-f546fb9c47e9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjY5NTIsIm5iZiI6MTcyNzE2NjY1MiwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwMTc5MDgwLWJlMDdjMGI5LTk2ZjAtNDc2My1hYzgyLWY1NDZmYjljNDdlOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIwYWQ5OTQ3NTFmYzNlNDQ4OTllN2RmMGFjYzI1Yjc2NzVlZDliNzFkMGRmMDUxMGUzZmM3ZmEzOGVlYzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q3ruS9yGDt13drtE9_NCEkwfzzcr4nZth1yXIgXS9IA) [ ](https://private-user-images.githubusercontent.com/131574323/370179080-be07c0b9-96f0-4763-ac82-f546fb9c47e9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjY5NTIsIm5iZiI6MTcyNzE2NjY1MiwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwMTc5MDgwLWJlMDdjMGI5LTk2ZjAtNDc2My1hYzgyLWY1NDZmYjljNDdlOS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwODMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGIwYWQ5OTQ3NTFmYzNlNDQ4OTllN2RmMGFjYzI1Yjc2NzVlZDliNzFkMGRmMDUxMGUzZmM3ZmEzOGVlYzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q3ruS9yGDt13drtE9_NCEkwfzzcr4nZth1yXIgXS9IA)

附上Outlook版本截图：
![Snipaste_2024-09-24_16-32-08](https://github.com/user-attachments/assets/f80ff4db-dd6c-4133-b87f-dba0d1e96c15)

**Comment by abgox** [comment]
- 我使用的是这个 Outlook
- 在 Microsoft 365 中打开 Outlook 会直接跳转到浏览器打开
![image](https://github.com/user-attachments/assets/20c5a113-d42e-4046-8eb1-802c48bff738)

**Comment by abgox** [comment]
2.21.10 版本尝试修复
如果问题仍然存在，请重开这个 issue

**Comment by kai06** [comment]
2.21.11测试结果：地址栏删除人名的问题已解决。
