### ISSUE TITLE
[Bug]: win10选中开机自启动报错

### ISSUE THREAD

**Issue by zhugeshu10086** [abgox/InputTip#60]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.10

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

InputTip

### bug 复现步骤

在底栏中右键InputTip,选择开机自启动,出现报错窗口

Error: (2) 系统找不到指定的文件。

▶	819: FileDelete(A_Startup "\InputTip.lnk")

Call stack:
*#1 (819) : [FileDelete] FileDelete(A_Startup "\InputTip.lnk")
*#1 (819) : [fn_startup] FileDelete(A_Startup "\InputTip.lnk")
> Menu
*#1 (761) : [Sleep] Sleep(50)
*#1 (761) : [] Sleep(50)
> Auto-execute

### 期望结果

打开开机自启动功能,即使每次开机都要给一次权限也比手动打开软件好

### 实际发生了什么?

开机并不会自启动
![image](https://github.com/user-attachments/assets/9754d33b-18b3-4df9-a290-aca93256759e)

### 还有其他你想要补充的信息吗？

我认为是快捷方式生成出错了,因为我的目录内并没有.lnk文件,有一个类型为快捷方式的文件竟然没有后缀,运行也没有反应

**Comment by abgox** [comment]
- 已经在 `2.21.11` 版本中修复
