### ISSUE TITLE
[Bug]: InputTip运行时，无法调音量

### ISSUE THREAD

**Issue by hiforrest** [abgox/InputTip#63]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.11

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

系统音量调节功能

### bug 复现步骤

https://github.com/user-attachments/assets/16da69c7-fb2e-4eba-8c91-8b9f2b33a993

### 期望结果

应该可以调节音量

### 实际发生了什么?

音量调节拖动手柄无法拖动，而且输入法会报错（搜狗拼音）

**Comment by abgox** [comment]
- 群里有朋友测试了，没有复现问题
![6bd9102aa4240fec680787121e43d8f8](https://github.com/user-attachments/assets/a9c1da7e-9ee9-47e9-8079-0494290eaebc)

**Comment by abgox** [comment]
- 搜狗输入法是最新版本吗？

**Comment by hiforrest** [comment]
搜狗输入法14.8.0正式版
14.8.0.9884
