### ISSUE TITLE
[Bug]: 运行InputTip的时候打开PotPlayer会闪退

### ISSUE THREAD

**Issue by hiforrest** [abgox/InputTip#64]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.21.11

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

PotPlayerMini64.exe

### bug 复现步骤

运行 InputTip.exe，打开 PotPlayer

https://github.com/user-attachments/assets/d7a92911-4690-48ea-a38a-814e8fdd61e5

### 期望结果

应该可以正常使用PotPlayer

### 实际发生了什么?

PotPlayer 闪退，退出 InputTip 则正常

**Comment by hiforrest** [comment]
发现可以通过「指定隐藏符号的应用」排除 Potplayer 来避免此 Bug 发生

**Comment by abgox** [comment]
Potplayer  中本身也没有输入场景，后面的版本，我就直接在软件内部把它禁了

**Comment by hiforrest** [comment]
> Potplayer 中本身也没有输入场景，后面的版本，我就直接在软件内部把它禁了

Potplayer 还是有一点输入场景的：播放列表，不过影响不大👌

**Comment by abgox** [comment]
- `2.22.0` 中，内部禁用了
