### ISSUE TITLE
[求助]: 请问能不能/怎么修改office&wps下的鼠标指针样式?

### ISSUE THREAD

**Issue by hhuimie** [abgox/InputTip#66]
### 描述这个功能请求

这是一个求助贴, 鼠标样式下, 使用office/wps软件, 大部分时候都会显示默认的鼠标指针样式, 请问能不能/怎么修改office&wps下的鼠标指针样式? 还是说是我版本问题
excel
![image](https://github.com/user-attachments/assets/7d9a39b9-2815-4c3c-b3b8-cfaeb287c969)
![image](https://github.com/user-attachments/assets/43cfdb71-20e2-40e8-abf3-a635e1a2799e)
![image](https://github.com/user-attachments/assets/82229576-4dbb-457e-84fa-d9b5ff620c68)

word
![image](https://github.com/user-attachments/assets/752938f4-f24e-46e5-ab91-782316a622c9)
![image](https://github.com/user-attachments/assets/9ad75baf-e23b-41c2-b31c-c8479eab0f1e)
![image](https://github.com/user-attachments/assets/4122d6ac-6dc0-4599-b9a0-abb50cc1405a)

### 你正在使用什么 Windows 系统版本?

Windows 10

**Comment by abgox** [comment]
- 实际上，系统级的鼠标样式是替换了的，但是这些软件在自己的窗口搞了一套鼠标样式，把系统样式覆盖掉了
- 这是没有办法解决的
