### ISSUE TITLE
[Bug]: 每次开机都弹出运行出错窗口。

### ISSUE THREAD

**Issue by zittr** [abgox/InputTip#67]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.22.0

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

InputTip.exe

### bug 复现步骤

1. 每次启动电脑都会弹出；
2. 直接点快捷方式会弹出；
3. 直接运行程序本体不会弹出。

### 期望结果

不要总是弹出这个警告。

### 实际发生了什么?

![PP_24-09-25_10-56-17](https://github.com/user-attachments/assets/5c81381b-d811-47fb-ae97-ed7c13f89416)
Error: Failed attempt to launch program or document:
Action: <powershell -NoProfile -Command $action = New-ScheduledTaskAction -Execute "D:\softnol\inPut\InputTip.exe";$principal = New-ScheduledTaskPrincipal -UserId "citta" -LogonType ServiceAccount -RunLevel Highest;$task = New-ScheduledTask -Action $action -Principal $principal;Register-ScheduledTask -TaskName "abgox.InputTip.noUAC" -InputObject $task -Force>
Params: <>

Specifically: 系统找不到指定的文件。

▶	240: RunWait('powershell -NoProfile -Command $action = New-ScheduledTaskAction -Execute "' A_ScriptFullPath '";$principal = New-ScheduledTaskPrincipal -UserId "' A_UserName '" -LogonType ServiceAccount -RunLevel Highest;$task = New-ScheduledTask -Action $action -Principal $principal;Register-ScheduledTask -TaskName "abgox.InputTip.noUAC" -InputObject $task -Force', , "Hide")

Call stack:
*#1 (240) : [RunWait] RunWait('powershell -NoProfile -Command $action = New-ScheduledTaskAction -Execute "' A_ScriptFullPath '";$principal = New-ScheduledTaskPrincipal -UserId "' A_UserName '" -LogonType ServiceAccount -RunLevel Highest;$task = New-ScheduledTask -Action $action -Principal $principal;Register-ScheduledTask -TaskName "abgox.InputTip.noUAC" -InputObject $task -Force', , "Hide")
*#1 (240) : [] RunWait('powershell -NoProfile -Command $action = New-ScheduledTaskAction -Execute "' A_ScriptFullPath '";$principal = New-ScheduledTaskPrincipal -UserId "' A_UserName '" -LogonType ServiceAccount -RunLevel Highest;$task = New-ScheduledTask -Action $action -Principal $principal;Register-ScheduledTask -TaskName "abgox.InputTip.noUAC" -InputObject $task -Force', , "Hide")
> Auto-execute

**Comment by abgox** [comment]
- 我也是 Win11，和你的系统环境一致，我复现不了这个bug，我从来没有出现过这个报错
- 把除 `InputTip.exe` 以外的其他文件，如 `InputTip.ini`/`InputTipCursor` 等都删除，然后重新运行 `InputTip.exe` 试试呢？

**Comment by abgox** [comment]
- 新版本中应该没有这个报错了吧？
- 如果还有，请重开这个 issue
