### ISSUE TITLE
[Bug]: 在word中打字图片会循环放大\缩小

### ISSUE THREAD

**Issue by OnHaiping** [abgox/InputTip#68]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.22.1

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

InputTip.exe

### bug 复现步骤

![动画](https://github.com/user-attachments/assets/0e43577b-2351-45d4-aae9-4f0044ddcda4)
如图所示.....

### 期望结果

应该不会发生变动

### 实际发生了什么?

图片在循环放大

### 还有其他你想要补充的信息吗？

希望尽快修改

**Comment by abgox** [comment]
- 无法复现
- 不行的话，试试其他类型提示吧，方块符号、文本字符

**Comment by abgox** [comment]
- 在最新版本中应该已经修复此问题
- 如果仍有问题，请重开此 issue
