### ISSUE TITLE
[Bug]: 托盘右键菜单打开时按快捷键呼出其他软件不显示在最前且右键菜单必须点击选项才能关闭

### ISSUE THREAD

**Issue by duanluan** [abgox/InputTip#69]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.22.1

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

QQ.exe、WeChat.exe、Feishu.exe

### bug 复现步骤

- 托盘右键显示菜单
- 按 Ctrl+Alt+Z 显示 QQ 或按 Ctrl+Alt+W 显示微信或按 Ctrl+Shift+W 显示飞书

### 期望结果

对应快捷键的应用显示在最前面

### 实际发生了什么?

任务栏图标闪烁，但对应快捷键的应用没有显示在最前面。
托盘右键菜单点击其他地方无法关闭，必须选择其中一项。

**Comment by abgox** [comment]
- 这应该是  AHK 生成的托盘菜单的默认行为
- 这种情况也少见，如果遇到了，随便点一个，再叉掉就好了
