### ISSUE TITLE
提示色块描边

### ISSUE THREAD

**Issue by gbsix** [abgox/InputTip#7]
提示色块可否添加描边，可以自定义描边的颜色和粗细？这样色块显示就可以有更多玩法。

**Comment by abgox** [comment]
- 描边？边框？
- 不知道能不能实现，感觉也没有太大意义
- 这个色块只是用来提示的，没必要弄得太花里胡哨吧？

**Comment by abgox** [comment]
- 挺麻烦的，而且很难做到，对于大多数人来说，也不是刚需
  - 这个方块符号是通过 AHK 的 Gui 画出来的，是直接设置的背景颜色，要添加这样的边框的话，暂时没有想到什么好的办法
- 不过在最新的 `2.11.0` 版本中，我添加了三种边框样式，可以尝试一下

**Comment by abgox** [comment]
- 好像也可以做到，画两个 Gui 中重叠就行了

**Comment by abgox** [comment]
- 最新 `2.12.0` 版本中加了一个 `自定义样式边框`
- 这个报错，我也不清楚，软件里中的代码逻辑都没有涉及到 `explorer.exe`(文件管理器)，理论上应该不是软件的问题

**Comment by Gaays** [comment]
边框能否做成配置项，感觉没必要，太突兀了，此外这个边框能否实现鼠标穿透效果？有些软件内输入框，即使设置了方块偏移，还是会出现在鼠标点击位置附近，点击事件落到本软件上了，导致点击激活目标输入框失败。

**Comment by abgox** [comment]
- `设置方块符号边框` 中，是有 `去掉边框样式` 的按钮的
- 在下个版本中，只要将对应的字符设置为空，就不会显示了
