### ISSUE TITLE
[Bug]: 使用手心输入法时，使用shift切换中英文输入法，不能触发指示符正确切换

### ISSUE THREAD

**Issue by mangguo7** [abgox/InputTip#70]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.22.1

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

手心输入法

### bug 复现步骤

这里使用了两个语言，一个中文语言，一个英语美国
1. 使用win+space键在两个语言之间切换时，软件是有效的
2. 在使用手心输入法时，使用ctrl+space进行中英切换，软件是有效的  
3. 在使用手心输入法时，使用shift进行中英切换，软件是失效的，只保持中文状态

### 期望结果

正常切换

### 实际发生了什么?

![动画](https://github.com/user-attachments/assets/c460db09-feab-433a-a107-38737015c826)

**Comment by abgox** [comment]
- `托盘菜单` => `设置输入法模式` => `模式4`

**Comment by mangguo7** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by abgox** [comment]
![recording](https://github.com/user-attachments/assets/2ac6183f-280c-44d5-9dd2-500e9917976d)

**Comment by mangguo7** [comment]
> ![recording](https://private-user-images.githubusercontent.com/131574323/370710062-2ac6183f-280c-44d5-9dd2-500e9917976d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzg5MDAsIm5iZiI6MTcyNzMzODYwMCwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwNzEwMDYyLTJhYzYxODNmLTI4MGMtNDRkNS05ZGQyLTUwMGU5OTE3OTc2ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWIzNDlmMjc0NDZlYjgzYzM5NTk1ZDU1YTcxNmI4NzNhNTcwZjFhMTU4YWI2NTViOTM2N2IxMjkzOWE5MjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4k28fI7GDCRFnpT9qRuIFfWRzV2-sCfLKVEhIC0tioQ) [ ![recording](https://private-user-images.githubusercontent.com/131574323/370710062-2ac6183f-280c-44d5-9dd2-500e9917976d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzg5MDAsIm5iZiI6MTcyNzMzODYwMCwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwNzEwMDYyLTJhYzYxODNmLTI4MGMtNDRkNS05ZGQyLTUwMGU5OTE3OTc2ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWIzNDlmMjc0NDZlYjgzYzM5NTk1ZDU1YTcxNmI4NzNhNTcwZjFhMTU4YWI2NTViOTM2N2IxMjkzOWE5MjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4k28fI7GDCRFnpT9qRuIFfWRzV2-sCfLKVEhIC0tioQ) ](https://private-user-images.githubusercontent.com/131574323/370710062-2ac6183f-280c-44d5-9dd2-500e9917976d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzg5MDAsIm5iZiI6MTcyNzMzODYwMCwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwNzEwMDYyLTJhYzYxODNmLTI4MGMtNDRkNS05ZGQyLTUwMGU5OTE3OTc2ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWIzNDlmMjc0NDZlYjgzYzM5NTk1ZDU1YTcxNmI4NzNhNTcwZjFhMTU4YWI2NTViOTM2N2IxMjkzOWE5MjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4k28fI7GDCRFnpT9qRuIFfWRzV2-sCfLKVEhIC0tioQ) [ ](https://private-user-images.githubusercontent.com/131574323/370710062-2ac6183f-280c-44d5-9dd2-500e9917976d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzg5MDAsIm5iZiI6MTcyNzMzODYwMCwicGF0aCI6Ii8xMzE1NzQzMjMvMzcwNzEwMDYyLTJhYzYxODNmLTI4MGMtNDRkNS05ZGQyLTUwMGU5OTE3OTc2ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWIzNDlmMjc0NDZlYjgzYzM5NTk1ZDU1YTcxNmI4NzNhNTcwZjFhMTU4YWI2NTViOTM2N2IxMjkzOWE5MjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4k28fI7GDCRFnpT9qRuIFfWRzV2-sCfLKVEhIC0tioQ)

太棒了，解决了。可能是excel的问题，只有在excel是无效的。
