### ISSUE TITLE
[Bug]: InputTip文件路径里有空格，开机自启动失败。

### ISSUE THREAD

**Issue by Sowari** [abgox/InputTip#72]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.22.2

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

InputTip

### bug 复现步骤

选中“开机自启动”后开机不会自己启动。任务计划程序中显示上次运行结果“系统找不到指定的文件(0x80070002)”

### 期望结果

可以正常开机自启动

### 实际发生了什么?

InputTip启动时会创建任务计划“abgox.InputTip.noUAC”用于自启动，我的InputTip文件路径是“D:\Program Files\InputTip\InputTip.exe”，其中有个空格，导致创建的任务计划无法启动，具体看下面图片。
![abgox InputTip noUAC任务计划-编辑操作-异常](https://github.com/user-attachments/assets/7de791e9-af3a-4d2d-ab4f-082daefd36db)

### 还有其他你想要补充的信息吗？

使用双引号把整个路径包裹起来之后可以正常启动。
![abgox InputTip noUAC任务计划-编辑操作-正常](https://github.com/user-attachments/assets/8bdc313a-7246-4ddb-816c-88989d40a4a7)

**Comment by abgox** [comment]
- 在 `2.22.3` 版本中已修复
