### ISSUE TITLE
[Bug]: idea 支持有问题

### ISSUE THREAD

**Issue by huo-feng-ding** [abgox/InputTip#73]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.22.4

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

idea64.exe

### bug 复现步骤

2.22.4 这个版本在开启对idea的支持后，但是在idea下不显示方块。 看了一下具体原因是InputTipSymbol.zip这个压缩包里的InputTip.JAB.JetBrains.exe这个程序应该不是最新的，在启动对idea的支持的时候，没有成功在后台运行这个程序

### 实际发生了什么?

在idea下什么都没显示

**Comment by abgox** [comment]
- 更新到 `2.22.5` 版本再试试
- 可以来回勾选几次 `启用 JetBrains IDE 支持`，然后 `重启`
- 打开任务管理器，搜索 `InputTip` 看看 InputTip.JAB.JetBrains.exe 它是否正常启动
