### ISSUE TITLE
[Bug]: win10安装完成后调节音频滚轮无法使用，系统自带的截图cart+shift+S卡死

### ISSUE THREAD

**Issue by ccchhhyyy666** [abgox/InputTip#76]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.23.0

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

win10的音频控制,截图

### bug 复现步骤

win10安装完成后调节音频滚轮无法使用，系统自带的截图cart+shift+S卡死

### 实际发生了什么?

win10安装完成后调节音频滚轮无法使用，系统自带的截图cart+shift+S卡死

**Comment by abgox** [comment]
- 我在虚拟机中测试过，没有复现问题
- 你可以将 `SnippingTool.exe` 和  `explorer.exe` 添加到 `符号显示黑名单` 中暂时规避问题
