### ISSUE TITLE
[Request]: 添加自动更新功能

### ISSUE THREAD

**Issue by huo-feng-ding** [abgox/InputTip#78]
### 描述这个功能请求

软件添加一个 自动更新 的功能，不然每次都要在官网看是不是有新的版本了，感觉很麻烦。直接添加自动更新功能，进行更新。

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- 如果没有勾选 `托盘菜单` 中的 `忽略更新`，默认是有自动检测更新的
- 当每次启动或重启 `InputTIp` 的时候都会检测更新，如果有更新，会有更新确认弹窗
