### ISSUE TITLE
[Bug]: 放大屏幕鼠标会变回去

### ISSUE THREAD

**Issue by xkaaaaa** [abgox/InputTip#79]
### 你应该确保已经完成了下面这些事情。

- [x] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

最新

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

放大镜

### bug 复现步骤

按win + +放大屏幕后，鼠标会变回原来的样式，点击任务栏会恢复

### 实际发生了什么?

/

**Comment by abgox** [comment]
- 使用放大镜时，放大镜应用应该会接管鼠标样式
- 不过放大镜这个应用不存在输入场景，退出放大镜后鼠标样式会重新生效，所以没有影响
