### ISSUE TITLE
Quiker 显示方块符号会自动清除用户输入文本框内的默认内容

### ISSUE THREAD

**Issue by Ponui** [abgox/InputTip#8]
版本：2.13.0

**Comment by abgox** [comment]
- 能否更详细的问题说明？ 或者有复现步骤？

**Comment by Ponui** [comment]
打开Quiker动作，有输入文本框的地方，会把默认的内容删除
![2024-09-16](https://github.com/user-attachments/assets/69bc5927-6987-478f-a9ea-05c867e16a43)
默认内容一闪而过，把方块符号关了就不会消失了。
![tmp795](https://github.com/user-attachments/assets/0cab4377-26d4-4a5a-aa2e-afbedf430c3a)

**Comment by abgox** [comment]
你测试用的这个 quicker 动作，有办法让我使用吗？这样我能更好的去复现这个 bug

**Comment by Ponui** [comment]
[测试.json](https://github.com/user-attachments/files/17012780/_20240916_202124.json)
右键导入就好
![tmp7AF2](https://github.com/user-attachments/assets/bc0d039d-45f5-48d0-b3b4-2333abfa17f6)

**Comment by abgox** [comment]
- 试了一下，应该是获取窗口中光标的方法，导致了内容被删除。但是获取位置会自动删除内容，奇奇怪怪的问题
- 只能暂时将 quiker 中的方块符号隐藏掉
   - 这样就不会触发获取窗口中光标位置的方法了
![image](https://github.com/user-attachments/assets/1fa5767f-0915-4f15-a9df-37c93d27f45a)
