### ISSUE TITLE
[Bug]: 小狼毫输入法中英文切换之后无法正常显示，一直显示中文，我已经选择了模式2，我是win10系统

### ISSUE THREAD

**Issue by cmdblock** [abgox/InputTip#80]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2.23.3

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

小狼毫输入法

### bug 复现步骤

小狼毫输入法中英文切换之后无法正常显示，一直显示中文，我已经选择了模式2，我是win10系统

### 实际发生了什么?

![PixPin_2024-10-07_00-30-38](https://github.com/user-attachments/assets/ec7591d1-00eb-4398-ab96-8bb7fc2c33f9)

**Comment by abgox** [comment]
- `模式2` 是有概率失效的，不过一般情况只要重新启动对应的应用程序就可以了
- 重新启动你这个记事本软件试试？

**Comment by huo-feng-ding** [comment]
这个应该是小狼毫的问题没有改状态，所以inputip取到的状态标识还是旧的导致的
