### ISSUE TITLE
[Request]: exe 文件加上Publisher 信息 （方便通过公司电脑Microsoft Defender SmartScreen）

### ISSUE THREAD

**Issue by gentleandy** [abgox/InputTip#81]
### 描述这个功能请求

这个软件超棒的，非常好用，但是在我公司的电脑上就运行不了，因为有安全要求，如果可以就加上Publisher 信息。
![image](https://github.com/user-attachments/assets/e0627e0f-14e4-41bd-8743-6c9883c3ccc4)

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- Publisher 信息？软件签名吗？不太了解
- 不能直接将 `InputTip.exe` 排除在外吗

**Comment by gentleandy** [comment]
是的，应该就是软件签名，目前是unknown publisher

**Comment by abgox** [comment]
- 可能你需要找方法将 InputTip 排除在外
- 软件签名应该不会做，签名价格昂贵，且是按年算的，这只是一个开源项目，不会负担这样的花销

**Comment by abgox** [comment]
- 目前发现，如果使用 Scoop 安装的话，是可以正常运行的
- 你可以尝试通过 Scoop 安装，InputTip 的应用清单在 [abgo_bucket](https://github.com/abgox/abgo_bucket) 这个 bucket 中
