### ISSUE TITLE
[Bug]: 打开报错

### ISSUE THREAD

**Issue by songxff** [abgox/InputTip#82]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.23.3

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

启动报错

### bug 复现步骤

![image](https://github.com/user-attachments/assets/0a4050af-8867-4fef-8fc5-ef49a64d7e0e)

### 期望结果

成功启动

### 实际发生了什么?

启动报错

**Comment by abgox** [comment]
- 是很老的 win10 系统版本吗？win10应该基本都包含这个 win32 api了吧
- 这个api 是在 `User32.dll` 这个动态链接库文件中，试试更新它呢？
