### ISSUE TITLE
[Bug]: chrome浏览器设置成自动切换英文状态过一会儿就失效了

### ISSUE THREAD

**Issue by huo-feng-ding** [abgox/InputTip#83]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.23.3

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

chrome

### bug 复现步骤

将chrome浏览器设置成自动切换英文状态，刚开始还能正确的切成英文状态，但是在用了一段时间后，发现切到chrome浏览器时不能正确的切成英文状态。
我使用的是搜狗五笔输入法。

### 实际发生了什么?

chrome设置成自动切换英文状态，用了一段时间后，切到chrome浏览器时自动切换英文状态失效，方块显示的是英文状态，但是输入的时候是中文状态; 另外试了idea也有类似的问题。
TIM我设置成自动切换中文状态，这个没有问题，一直都是正确的。

**Comment by abgox** [comment]
- 输入法模式是否使用的是 `模式2`？
- `模式2` 虽然兼容的输入法、应用更广，但有时候可能会失效，进而导致自动切换失效
- 搜狗五笔输入法的话，试试 `模式1` 吧

**Comment by abgox** [comment]
- 下载搜狗五笔输入法试过了，在 `模式2` 的情况下，chorme 的自动切换正常，无法复现问题

**Comment by huo-feng-ding** [comment]
我是这样操作，先在chrome下切到中文状态，然后再切到vscode应用窗口，idea应用窗口，terminal应用窗口等，切一圈窗口回来后，再切回到chrome应该窗口下，此时方块显示的是英文状态，但是输入法实际是中文状态

**Comment by abgox** [comment]
我就是这样试的，但是在我的电脑中一切正常，无法复现

**Comment by catvox** [comment]
我感觉是新的windows11 24h2的问题。我两台24h2同样的问题，win10倒是正常。
