### ISSUE TITLE
[Bug]: VS2022 方块无法跟随输入点，总是显示在左上角，如果开了两个窗口，显示位置还不一样

### ISSUE THREAD

**Issue by cethink** [abgox/InputTip#85]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.23.5

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

devenv.exe

### bug 复现步骤

![image](https://github.com/user-attachments/assets/5d4545a0-6b96-4b20-adf8-e1ca72d546f6)
![image](https://github.com/user-attachments/assets/9894c220-2902-4879-9ce0-a8eb0aa102d5)

### 实际发生了什么?

见图

**Comment by abgox** [comment]
- `2.24.0` 版本中适配
