### ISSUE TITLE
[Request]: 命令提示符输入改进

### ISSUE THREAD

**Issue by cyy-2024** [abgox/InputTip#86]
### 描述这个功能请求

在使用该软件时，我发现有时在命令提示符中输入，尤其是进行删除操作时，鼠标会自动消失，且颜色方块没有显示。不确定这是否为软件本身的问题，还是我的操作方式不当。如果能对此进行改进或提供一些建议，我将非常感谢。期待您的回复！

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- 当输入内容时，鼠标隐藏，这是一些软件以及系统的默认行为
- 符号显示是正常的
![recording](https://github.com/user-attachments/assets/58a2fc94-a85b-4733-a3e8-fa1c3ebe3261)
