### ISSUE TITLE
[Bug]: 开机自启动在未接通电源时不可用

### ISSUE THREAD

**Issue by DBaob** [abgox/InputTip#87]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2.23.5

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

InputTip.exe

### bug 复现步骤

不连接充电器时开机，InputTip不能自启动

### 实际发生了什么?

不连接充电器时开机，InputTip不能自启动；
只有在接通电源时，InputTip才能自启动

**Comment by abgox** [comment]
- `2.24.0` 版本中修复
