### ISSUE TITLE
[Bug]: windows自带的照片软件，打开图片就闪退。暂停inputTip软件就可以用了。

### ISSUE THREAD

**Issue by mxhou** [abgox/InputTip#88]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.24.0

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

PhotosService.exe

### bug 复现步骤

 windows自带的照片软件，打开图片就闪退。暂停inputTip软件就可以用了。

### 实际发生了什么?

 windows自带的照片软件，打开图片就闪退。暂停inputTip软件就可以用了。

### 还有其他你想要补充的信息吗？

 windows自带的照片软件，打开图片就闪退。暂停inputTip软件就可以用了。

**Comment by abgox** [comment]
- Win 10 的兼容性问题，添加 `符号显示黑名单` 即可

**Comment by mxhou** [comment]
![image](https://github.com/user-attachments/assets/b2e98b18-b408-47eb-a46a-e37e2353d296
![屏幕截图 2024-10-19 133851](https://github.com/user-attachments/assets/71abf290-fb1c-45de-a298-4b0a3c04bee0)
已经添加过了 两三秒后还是闪退 此方案不行
