### ISSUE TITLE
[Request]: 请增加更多语言设置

### ISSUE THREAD

**Issue by EaglePPP** [abgox/InputTip#89]
### 描述这个功能请求

请增加更多语言设置（多布局
~~现在如果有除了中英文的其他语言那么会发生bug
英语也会变为中文的符号~~  ~~不知道为什么又好了~~
我有5个输入法，不知道和这个有没有关系。前两个是中文符号，后面三个是英文符号
![image](https://github.com/user-attachments/assets/aee4ccf1-958b-4287-8c7a-b27e541bb9f1)

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- 目前 `InputTip` 只支持中英文
- 后续添加多语言的可能性不大
