### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ressler-Git** [abgox/InputTip#91]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

v2.24.0

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

winword.exe

### bug 复现步骤

![1](https://github.com/user-attachments/assets/87d64c2d-a6ca-4992-93bc-30ddc529d81c)
在Windows11下面使用Office2021版本，在Word里面输入法的状态跟实际刚好相反，例如在Word里面是中文输入状态的时候显示在英文，在英文输入状态的时候显示为中文。在其他软件里面都是正常的，唯独这个刚好相反。重启Office软件之后还是一样，持续出现。

### 实际发生了什么?

![1](https://github.com/user-attachments/assets/7da812b8-1069-4e70-9b85-957bf486af74)
在Windows11下面使用Office2021版本，在Word里面输入法的状态跟实际刚好相反，例如在Word里面是中文输入状态的时候显示在英文，在英文输入状态的时候显示为中文。在其他软件里面都是正常的，唯独这个刚好相反。

**Comment by abgox** [comment]
- 使用的什么输入法？
- 尝试切换 `输入法模式` 试试？

**Comment by Ressler-Git** [comment]
> * 使用的什么输入法？
> * 尝试切换 `输入法模式` 试试？

使用的是冰凌输入法，尝试过切换“输入法模式”都不起作用，现在尝试将冰凌输入法切换到微信输入法就正常了。很奇怪的是使用冰凌输入法在其他任何地方都是正确的，包括在Excel里面也是正常的，唯独就在Word里面显示的刚好相反。
另外每次开机启动的时候会弹图片所示的提示（已经尝试过点击查看证书并安装，下次依旧会有这个弹窗），有办法解决不弹吗？感谢！
![000](https://github.com/user-attachments/assets/07758d35-1aa1-4e57-8548-68ee414afe03)

**Comment by abgox** [comment]
> > * 使用的什么输入法？
> > * 尝试切换 `输入法模式` 试试？
> 
> 使用的是冰凌输入法，尝试过切换“输入法模式”都不起作用，现在尝试将冰凌输入法切换到微信输入法就正常了。很奇怪的是使用冰凌输入法在其他任何地方都是正确的，包括在Excel里面也是正常的，唯独就在Word里面显示的刚好相反。 另外每次开机启动的时候会弹图片所示的提示（已经尝试过点击查看证书并安装，下次依旧会有这个弹窗），有办法解决不弹吗？感谢！ ![000](https://private-user-images.githubusercontent.com/24690612/381348179-07758d35-1aa1-4e57-8548-68ee414afe03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MDcxMDgsIm5iZiI6MTczNTcwNjgwOCwicGF0aCI6Ii8yNDY5MDYxMi8zODEzNDgxNzktMDc3NThkMzUtMWFhMS00ZTU3LTg1NDgtNjhlZTQxNGFmZTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDA0NDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MWFlNmNmNjY4NWJjNTkzOTM2Y2I2MjNlMzM1YzJiMTUxOGJiYzkxOGMzMzgwNDI2MDUxMzM4NWI5ZDI4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W5zBz2uB2myAplgS8grOOJW6u7hoFeKvZcyg598DQXA)

- @Ressler-Git 这个问题，目前已经知道是为什么了。
- 你应该使用的是第三方精简过的系统
- 出现这个问题是因为，InputTip 启动时会有网络请求(尝试访问 github、gitee)
- 而精简后的系统，移除了根证书，导致 github.com 和 gitee.com 不能正确识别
- 这个不是 InputTip 的问题
- 但是 `2.28.1` 版本中也可以将更新间隔设置为 0，也就是旧版本的忽略更新。
- 这样就不会有网络请求，从而避免这个问题
