### ISSUE TITLE
[Bug]: 打开报错

### ISSUE THREAD

**Issue by 389212263** [abgox/InputTip#92]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.24.0

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

打开报错

### bug 复现步骤

打开报错，公司的电脑

### 实际发生了什么?

![image](https://github.com/user-attachments/assets/36b77367-6af4-4de5-aa70-68c9590900d8)

**Comment by 389212263** [comment]
第一次运行，报这个错，然后不起作用；删了重新下载，运行，还是报错，但是起作用了

**Comment by abgox** [comment]
- 电脑系统是否为第三方精简定制版本？
- 此问题在极个别用户中出现，且我无法复现

**Comment by abgox** [comment]
- 有可能是相关文件释放不出来的问题
- 试试最新版本 `v2.4.1`

**Comment by 389212263** [comment]
> * 电脑系统是否为第三方精简定制版本？
> * 此问题在极个别用户中出现，且我无法复现



> * 电脑系统是否为第三方精简定制版本？
> * 此问题在极个别用户中出现，且我无法复现

公司的电脑，应该是精简过的

**Comment by 389212263** [comment]
2.4.1也一样的报错

**Comment by abgox** [comment]
- 电脑中没有 `powershell` 或者访问不到 `powershell` 的问题
- 新版本有抑制这个报错，但根源性问题需要手动解决

![image](https://github.com/user-attachments/assets/4e889b2d-f7a9-4210-a3fb-c6f4759de992)
