### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PainKiller0x0** [abgox/InputTip#93]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.24.1

### 你正在使用什么 Windows 系统版本?

Windows 10

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

r5apex_dx12.exe

### bug 复现步骤

打开apex时必然报错，然后无法登录。
需要关闭inputip之后才能正常打开。
![QQ图片20241027144831](https://github.com/user-attachments/assets/c4c8b37d-047b-46b9-981b-2ac7fbbb2d77)

### 期望结果

期望不影响eac，eac在常见游戏中很泛用

### 实际发生了什么?

inputip导致了eac报错，从而无法进入apex。

**Comment by abgox** [comment]
- 建议在进入游戏前，`暂停软件运行`
- 或者将进程添加到 `符号显示黑名单` 中

**Comment by abgox** [comment]
- `v2.28.0` 中，可以设置一个快捷键，快速暂停和运行 `InputTip`
- 对于游戏类应用，进入游戏前，先使用快捷键暂停 `InputTip` 可能更好

**Comment by o7451** [comment]
原来如此，我也是排除变量后才知道会被imputtip认为是外挂程序

**Comment by Yia-wooh** [comment]
> * `v2.28.0` 中，可以设置一个快捷键，快速暂停和运行 `InputTip`
> * 对于游戏类应用，进入游戏前，先使用快捷键暂停 `InputTip` 可能更好

已实验，黑名单或暂停运行都会报错，目前只能退出后台

**Comment by abgox** [comment]
- 这取决于游戏官方对 AutoHotkey 的态度
- 如果游戏官方认为只要后台有 AutoHotkey 程序存在，就判断为外挂，那就只能选择退出 `InputTip`

**Comment by o7451** [comment]
> * 这取决于游戏官方对 AutoHotkey 的态度
> * 如果游戏官方认为只要后台有 AutoHotkey 程序存在，就判断为外挂，那就只能选择退出 `InputTip`

原来是基于AutoHotkey 吗，难怪AutoHotkey 的脚本同样被禁
