### ISSUE TITLE
[Request]: 仅在当前APP不常用的输入状态下 才提示+写注释时自动切换输入法

### ISSUE THREAD

**Issue by photkey** [abgox/InputTip#94]
### 描述这个功能请求

仅在当前APP不常用的输入状态下 才提示：可设置哪些软件、哪种状态下（中/英/大）不显示符号；
比方：在 notepad、微信、QQ等绝大多数情况下 使用中文输入法的应用中，中文状态下就不显示符号了，只有英文或者大写的时候 才显示；
比方在 cmd、VScode 等绝大多数情况下 都是使用英文输入法的应用中，英文状态下就不显示符号了，只有中文或者大写的时候才显示；
这样提示符号 就既可以在平时不打扰，又能在关键时刻及时提醒（切换到不常用状态时）

自动切换输入法增强：
在vscode或者其他编辑器中，按一些特殊的按键 可以自动切换输入法；比方我常用vim插件，需要的是按ESC 自动切换英文；
而且当在这些应用中，还可以设置写注释时 自动切换为中文输入法，比方 `;空格` 就自动输入中文；
如果不会占用过多资源的话 可以更细致一点：
标题中 含有`.ahk`时 输入`;空格` 才切换中文，标题中含有`.py` 时 输入 `#空格` 自动切换中文 等等，把主流编程语言文件后缀名跟注释符号 对应一下。

### 你正在使用什么 Windows 系统版本?

Windows 11

**Comment by abgox** [comment]
- `InputTIp` 更强调实时显示
- 如果接受不了视觉干扰，可能 [ImTip](https://github.com/aardio/ImTip) 和 [KBLAutoSwitch](https://github.com/flyinclouds/KBLAutoSwitch) 更适合你
