### ISSUE TITLE
[Bug]: 分辨率变化，没有同步变化

### ISSUE THREAD

**Issue by qzwl** [abgox/InputTip#97]
### 你应该确保已经完成了下面这些事情。

- [X] 你已经阅读了项目的 README 文件。
- [X] 你已经在 [Issues](https://github.com/abgox/InputTip/issues) 中搜索了你遇到的问题，但没有找到相关 issue。
- [X] 你已经查看了 [一些常见的使用问题](https://inputtip.pages.dev/FAQ/), 其中没有你遇到的问题。

### 当前使用的 InputTip 版本

2.24.1

### 你正在使用什么 Windows 系统版本?

Windows 11

### 哪一个软件出现了问题?软件进程名叫什么？(比如：QQ.exe)

微信

### bug 复现步骤

就是被远程电脑4K屏幕，通过办公电脑1080P远程。导致标识变巨大。

### 期望结果

根据屏幕分辨率 自行调整。

### 实际发生了什么?

![Dingtalk_20241101144439](https://github.com/user-attachments/assets/1825aea4-a11f-4779-abcd-bb1b8dab750c)

**Comment by abgox** [comment]
- 试试 `v2.24.2`,对这种意外放大的场景有修复
